/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRWASecurityToken,
  IRWASecurityTokenInterface,
} from "../../../contracts/RWASecurityExchange.sol/IRWASecurityToken";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_account",
        type: "address",
      },
    ],
    name: "frozen",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_account",
        type: "address",
      },
    ],
    name: "isLocked",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IRWASecurityToken__factory {
  static readonly abi = _abi;
  static createInterface(): IRWASecurityTokenInterface {
    return new Interface(_abi) as IRWASecurityTokenInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IRWASecurityToken {
    return new Contract(address, _abi, runner) as unknown as IRWASecurityToken;
  }
}
