/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace KYCLib {
  export type KYCProofStruct = {
    level: BigNumberish;
    countryCode: BigNumberish;
    expiry: BigNumberish;
    signature: BytesLike;
  };

  export type KYCProofStructOutput = [
    level: bigint,
    countryCode: bigint,
    expiry: bigint,
    signature: string
  ] & { level: bigint; countryCode: bigint; expiry: bigint; signature: string };
}

export declare namespace RWATokenizationFactory {
  export type TokenDeploymentStruct = {
    deploymentId: BigNumberish;
    owner: AddressLike;
    securityToken: AddressLike;
    projectNFT: AddressLike;
    tradeEscrow: AddressLike;
    dividendDistributor: AddressLike;
    deploymentType: BigNumberish;
    deployedAt: BigNumberish;
    active: boolean;
    metadataURI: string;
    minKYCLevel: BigNumberish;
  };

  export type TokenDeploymentStructOutput = [
    deploymentId: bigint,
    owner: string,
    securityToken: string,
    projectNFT: string,
    tradeEscrow: string,
    dividendDistributor: string,
    deploymentType: bigint,
    deployedAt: bigint,
    active: boolean,
    metadataURI: string,
    minKYCLevel: bigint
  ] & {
    deploymentId: bigint;
    owner: string;
    securityToken: string;
    projectNFT: string;
    tradeEscrow: string;
    dividendDistributor: string;
    deploymentType: bigint;
    deployedAt: bigint;
    active: boolean;
    metadataURI: string;
    minKYCLevel: bigint;
  };

  export type ImplementationsStruct = {
    securityToken: AddressLike;
    projectNFT: AddressLike;
    compliance: AddressLike;
    tradeEscrow: AddressLike;
    dividendDistributor: AddressLike;
  };

  export type ImplementationsStructOutput = [
    securityToken: string,
    projectNFT: string,
    compliance: string,
    tradeEscrow: string,
    dividendDistributor: string
  ] & {
    securityToken: string;
    projectNFT: string;
    compliance: string;
    tradeEscrow: string;
    dividendDistributor: string;
  };
}

export interface RWATokenizationFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addDividendModule"
      | "addEscrow"
      | "approvedDeployers"
      | "deactivateDeployment"
      | "defaultRestrictedCountries"
      | "deployNFTAndToken"
      | "deployNFTAndTokenWithKYC"
      | "deployProjectNFT"
      | "deployToken"
      | "deployWithEscrow"
      | "deployWithEscrowAndKYC"
      | "deploymentCounter"
      | "deploymentRestrictedCountries"
      | "deployments"
      | "escrowTransactionFeeBps"
      | "getDefaultRestrictedCountries"
      | "getDeployment"
      | "getImplementations"
      | "getKYCVerifier"
      | "getOwnerDeploymentCount"
      | "getOwnerDeployments"
      | "implementations"
      | "initialize"
      | "isDeployerApproved"
      | "kycVerifier"
      | "minKYCLevelForDeployment"
      | "owner"
      | "ownerDeployments"
      | "pause"
      | "paused"
      | "platformFeeRecipient"
      | "proxiableUUID"
      | "renounceOwnership"
      | "requireApproval"
      | "requireKYCForDeployment"
      | "setComplianceImplementation"
      | "setDeployerApproval"
      | "setDividendDistributorImplementation"
      | "setEscrowTransactionFee"
      | "setKYCRequirement"
      | "setKYCVerifier"
      | "setPlatformFeeRecipient"
      | "setProjectNFTImplementation"
      | "setRequireApproval"
      | "setSecurityTokenImplementation"
      | "setTradeEscrowImplementation"
      | "transferOwnership"
      | "unpause"
      | "upgradeTo"
      | "upgradeToAndCall"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdminChanged"
      | "BeaconUpgraded"
      | "DeployerApprovalUpdated"
      | "DeploymentDeactivated"
      | "DividendModuleDeployed"
      | "EscrowDeployed"
      | "ImplementationUpdated"
      | "Initialized"
      | "KYCVerifierUpdated"
      | "OwnershipTransferred"
      | "Paused"
      | "ProjectNFTDeployed"
      | "TokenDeployed"
      | "Unpaused"
      | "Upgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addDividendModule",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addEscrow",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "approvedDeployers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateDeployment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "defaultRestrictedCountries",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deployNFTAndToken",
    values: [string, string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "deployNFTAndTokenWithKYC",
    values: [
      string,
      string,
      BigNumberish,
      string,
      BigNumberish,
      KYCLib.KYCProofStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "deployProjectNFT",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "deployToken",
    values: [string, string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "deployWithEscrow",
    values: [string, string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "deployWithEscrowAndKYC",
    values: [
      string,
      string,
      BigNumberish,
      string,
      BigNumberish,
      KYCLib.KYCProofStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "deploymentCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deploymentRestrictedCountries",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deployments",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "escrowTransactionFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDefaultRestrictedCountries",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDeployment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getImplementations",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getKYCVerifier",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getOwnerDeploymentCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getOwnerDeployments",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "implementations",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "isDeployerApproved",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "kycVerifier",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minKYCLevelForDeployment",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerDeployments",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformFeeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requireApproval",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requireKYCForDeployment",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setComplianceImplementation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setDeployerApproval",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setDividendDistributorImplementation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setEscrowTransactionFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setKYCRequirement",
    values: [boolean, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setKYCVerifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformFeeRecipient",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setProjectNFTImplementation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setRequireApproval",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setSecurityTokenImplementation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTradeEscrowImplementation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "upgradeTo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addDividendModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addEscrow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "approvedDeployers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateDeployment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "defaultRestrictedCountries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployNFTAndToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployNFTAndTokenWithKYC",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployProjectNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployWithEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployWithEscrowAndKYC",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deploymentCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deploymentRestrictedCountries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "escrowTransactionFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDefaultRestrictedCountries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDeployment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getImplementations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getKYCVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOwnerDeploymentCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOwnerDeployments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "implementations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isDeployerApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "kycVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minKYCLevelForDeployment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ownerDeployments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requireApproval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requireKYCForDeployment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setComplianceImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDeployerApproval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDividendDistributorImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setEscrowTransactionFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setKYCRequirement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setKYCVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProjectNFTImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRequireApproval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSecurityTokenImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTradeEscrowImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "upgradeTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
}

export namespace AdminChangedEvent {
  export type InputTuple = [previousAdmin: AddressLike, newAdmin: AddressLike];
  export type OutputTuple = [previousAdmin: string, newAdmin: string];
  export interface OutputObject {
    previousAdmin: string;
    newAdmin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BeaconUpgradedEvent {
  export type InputTuple = [beacon: AddressLike];
  export type OutputTuple = [beacon: string];
  export interface OutputObject {
    beacon: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DeployerApprovalUpdatedEvent {
  export type InputTuple = [deployer: AddressLike, approved: boolean];
  export type OutputTuple = [deployer: string, approved: boolean];
  export interface OutputObject {
    deployer: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DeploymentDeactivatedEvent {
  export type InputTuple = [deploymentId: BigNumberish];
  export type OutputTuple = [deploymentId: bigint];
  export interface OutputObject {
    deploymentId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DividendModuleDeployedEvent {
  export type InputTuple = [
    deploymentId: BigNumberish,
    owner: AddressLike,
    dividendDistributor: AddressLike
  ];
  export type OutputTuple = [
    deploymentId: bigint,
    owner: string,
    dividendDistributor: string
  ];
  export interface OutputObject {
    deploymentId: bigint;
    owner: string;
    dividendDistributor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowDeployedEvent {
  export type InputTuple = [
    deploymentId: BigNumberish,
    owner: AddressLike,
    tradeEscrow: AddressLike
  ];
  export type OutputTuple = [
    deploymentId: bigint,
    owner: string,
    tradeEscrow: string
  ];
  export interface OutputObject {
    deploymentId: bigint;
    owner: string;
    tradeEscrow: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ImplementationUpdatedEvent {
  export type InputTuple = [
    contractType: string,
    oldImpl: AddressLike,
    newImpl: AddressLike
  ];
  export type OutputTuple = [
    contractType: string,
    oldImpl: string,
    newImpl: string
  ];
  export interface OutputObject {
    contractType: string;
    oldImpl: string;
    newImpl: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace KYCVerifierUpdatedEvent {
  export type InputTuple = [oldVerifier: AddressLike, newVerifier: AddressLike];
  export type OutputTuple = [oldVerifier: string, newVerifier: string];
  export interface OutputObject {
    oldVerifier: string;
    newVerifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProjectNFTDeployedEvent {
  export type InputTuple = [
    deploymentId: BigNumberish,
    owner: AddressLike,
    projectNFT: AddressLike,
    deploymentType: BigNumberish
  ];
  export type OutputTuple = [
    deploymentId: bigint,
    owner: string,
    projectNFT: string,
    deploymentType: bigint
  ];
  export interface OutputObject {
    deploymentId: bigint;
    owner: string;
    projectNFT: string;
    deploymentType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenDeployedEvent {
  export type InputTuple = [
    deploymentId: BigNumberish,
    owner: AddressLike,
    securityToken: AddressLike,
    supply: BigNumberish,
    deploymentType: BigNumberish,
    minKYCLevel: BigNumberish
  ];
  export type OutputTuple = [
    deploymentId: bigint,
    owner: string,
    securityToken: string,
    supply: bigint,
    deploymentType: bigint,
    minKYCLevel: bigint
  ];
  export interface OutputObject {
    deploymentId: bigint;
    owner: string;
    securityToken: string;
    supply: bigint;
    deploymentType: bigint;
    minKYCLevel: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RWATokenizationFactory extends BaseContract {
  connect(runner?: ContractRunner | null): RWATokenizationFactory;
  waitForDeployment(): Promise<this>;

  interface: RWATokenizationFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addDividendModule: TypedContractMethod<
    [_deploymentId: BigNumberish],
    [string],
    "nonpayable"
  >;

  addEscrow: TypedContractMethod<
    [_deploymentId: BigNumberish],
    [string],
    "nonpayable"
  >;

  approvedDeployers: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  deactivateDeployment: TypedContractMethod<
    [_id: BigNumberish],
    [void],
    "nonpayable"
  >;

  defaultRestrictedCountries: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  deployNFTAndToken: TypedContractMethod<
    [
      _name: string,
      _symbol: string,
      _supply: BigNumberish,
      _metadataURI: string
    ],
    [
      [bigint, string, string] & {
        deploymentId: bigint;
        securityToken: string;
        projectNFT: string;
      }
    ],
    "nonpayable"
  >;

  deployNFTAndTokenWithKYC: TypedContractMethod<
    [
      _name: string,
      _symbol: string,
      _supply: BigNumberish,
      _metadataURI: string,
      _minKYCLevel: BigNumberish,
      _kycProof: KYCLib.KYCProofStruct
    ],
    [
      [bigint, string, string] & {
        deploymentId: bigint;
        securityToken: string;
        projectNFT: string;
      }
    ],
    "nonpayable"
  >;

  deployProjectNFT: TypedContractMethod<
    [_name: string, _symbol: string, _metadataURI: string],
    [[bigint, string] & { deploymentId: bigint; projectNFT: string }],
    "nonpayable"
  >;

  deployToken: TypedContractMethod<
    [
      _name: string,
      _symbol: string,
      _supply: BigNumberish,
      _metadataURI: string
    ],
    [[bigint, string] & { deploymentId: bigint; securityToken: string }],
    "nonpayable"
  >;

  deployWithEscrow: TypedContractMethod<
    [
      _name: string,
      _symbol: string,
      _supply: BigNumberish,
      _metadataURI: string
    ],
    [
      [bigint, string, string, string] & {
        deploymentId: bigint;
        securityToken: string;
        projectNFT: string;
        tradeEscrow: string;
      }
    ],
    "nonpayable"
  >;

  deployWithEscrowAndKYC: TypedContractMethod<
    [
      _name: string,
      _symbol: string,
      _supply: BigNumberish,
      _metadataURI: string,
      _minKYCLevel: BigNumberish,
      _kycProof: KYCLib.KYCProofStruct
    ],
    [
      [bigint, string, string, string] & {
        deploymentId: bigint;
        securityToken: string;
        projectNFT: string;
        tradeEscrow: string;
      }
    ],
    "nonpayable"
  >;

  deploymentCounter: TypedContractMethod<[], [bigint], "view">;

  deploymentRestrictedCountries: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  deployments: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        boolean,
        string,
        bigint
      ] & {
        deploymentId: bigint;
        owner: string;
        securityToken: string;
        projectNFT: string;
        tradeEscrow: string;
        dividendDistributor: string;
        deploymentType: bigint;
        deployedAt: bigint;
        active: boolean;
        metadataURI: string;
        minKYCLevel: bigint;
      }
    ],
    "view"
  >;

  escrowTransactionFeeBps: TypedContractMethod<[], [bigint], "view">;

  getDefaultRestrictedCountries: TypedContractMethod<[], [bigint[]], "view">;

  getDeployment: TypedContractMethod<
    [_id: BigNumberish],
    [RWATokenizationFactory.TokenDeploymentStructOutput],
    "view"
  >;

  getImplementations: TypedContractMethod<
    [],
    [RWATokenizationFactory.ImplementationsStructOutput],
    "view"
  >;

  getKYCVerifier: TypedContractMethod<[], [string], "view">;

  getOwnerDeploymentCount: TypedContractMethod<
    [_o: AddressLike],
    [bigint],
    "view"
  >;

  getOwnerDeployments: TypedContractMethod<
    [_o: AddressLike],
    [bigint[]],
    "view"
  >;

  implementations: TypedContractMethod<
    [],
    [
      [string, string, string, string, string] & {
        securityToken: string;
        projectNFT: string;
        compliance: string;
        tradeEscrow: string;
        dividendDistributor: string;
      }
    ],
    "view"
  >;

  initialize: TypedContractMethod<
    [
      _admin: AddressLike,
      _securityTokenImpl: AddressLike,
      _projectNFTImpl: AddressLike,
      _complianceImpl: AddressLike,
      _kycVerifier: AddressLike,
      _feeRecipient: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  isDeployerApproved: TypedContractMethod<[_d: AddressLike], [boolean], "view">;

  kycVerifier: TypedContractMethod<[], [string], "view">;

  minKYCLevelForDeployment: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  ownerDeployments: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  platformFeeRecipient: TypedContractMethod<[], [string], "view">;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  requireApproval: TypedContractMethod<[], [boolean], "view">;

  requireKYCForDeployment: TypedContractMethod<[], [boolean], "view">;

  setComplianceImplementation: TypedContractMethod<
    [_impl: AddressLike],
    [void],
    "nonpayable"
  >;

  setDeployerApproval: TypedContractMethod<
    [_d: AddressLike, _a: boolean],
    [void],
    "nonpayable"
  >;

  setDividendDistributorImplementation: TypedContractMethod<
    [_impl: AddressLike],
    [void],
    "nonpayable"
  >;

  setEscrowTransactionFee: TypedContractMethod<
    [_feeBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  setKYCRequirement: TypedContractMethod<
    [_r: boolean, _l: BigNumberish],
    [void],
    "nonpayable"
  >;

  setKYCVerifier: TypedContractMethod<[_v: AddressLike], [void], "nonpayable">;

  setPlatformFeeRecipient: TypedContractMethod<
    [_r: AddressLike],
    [void],
    "nonpayable"
  >;

  setProjectNFTImplementation: TypedContractMethod<
    [_impl: AddressLike],
    [void],
    "nonpayable"
  >;

  setRequireApproval: TypedContractMethod<[_r: boolean], [void], "nonpayable">;

  setSecurityTokenImplementation: TypedContractMethod<
    [_impl: AddressLike],
    [void],
    "nonpayable"
  >;

  setTradeEscrowImplementation: TypedContractMethod<
    [_impl: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  upgradeTo: TypedContractMethod<
    [newImplementation: AddressLike],
    [void],
    "nonpayable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addDividendModule"
  ): TypedContractMethod<[_deploymentId: BigNumberish], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "addEscrow"
  ): TypedContractMethod<[_deploymentId: BigNumberish], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "approvedDeployers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "deactivateDeployment"
  ): TypedContractMethod<[_id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "defaultRestrictedCountries"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "deployNFTAndToken"
  ): TypedContractMethod<
    [
      _name: string,
      _symbol: string,
      _supply: BigNumberish,
      _metadataURI: string
    ],
    [
      [bigint, string, string] & {
        deploymentId: bigint;
        securityToken: string;
        projectNFT: string;
      }
    ],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deployNFTAndTokenWithKYC"
  ): TypedContractMethod<
    [
      _name: string,
      _symbol: string,
      _supply: BigNumberish,
      _metadataURI: string,
      _minKYCLevel: BigNumberish,
      _kycProof: KYCLib.KYCProofStruct
    ],
    [
      [bigint, string, string] & {
        deploymentId: bigint;
        securityToken: string;
        projectNFT: string;
      }
    ],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deployProjectNFT"
  ): TypedContractMethod<
    [_name: string, _symbol: string, _metadataURI: string],
    [[bigint, string] & { deploymentId: bigint; projectNFT: string }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deployToken"
  ): TypedContractMethod<
    [
      _name: string,
      _symbol: string,
      _supply: BigNumberish,
      _metadataURI: string
    ],
    [[bigint, string] & { deploymentId: bigint; securityToken: string }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deployWithEscrow"
  ): TypedContractMethod<
    [
      _name: string,
      _symbol: string,
      _supply: BigNumberish,
      _metadataURI: string
    ],
    [
      [bigint, string, string, string] & {
        deploymentId: bigint;
        securityToken: string;
        projectNFT: string;
        tradeEscrow: string;
      }
    ],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deployWithEscrowAndKYC"
  ): TypedContractMethod<
    [
      _name: string,
      _symbol: string,
      _supply: BigNumberish,
      _metadataURI: string,
      _minKYCLevel: BigNumberish,
      _kycProof: KYCLib.KYCProofStruct
    ],
    [
      [bigint, string, string, string] & {
        deploymentId: bigint;
        securityToken: string;
        projectNFT: string;
        tradeEscrow: string;
      }
    ],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deploymentCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deploymentRestrictedCountries"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "deployments"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        boolean,
        string,
        bigint
      ] & {
        deploymentId: bigint;
        owner: string;
        securityToken: string;
        projectNFT: string;
        tradeEscrow: string;
        dividendDistributor: string;
        deploymentType: bigint;
        deployedAt: bigint;
        active: boolean;
        metadataURI: string;
        minKYCLevel: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "escrowTransactionFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDefaultRestrictedCountries"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getDeployment"
  ): TypedContractMethod<
    [_id: BigNumberish],
    [RWATokenizationFactory.TokenDeploymentStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getImplementations"
  ): TypedContractMethod<
    [],
    [RWATokenizationFactory.ImplementationsStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getKYCVerifier"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getOwnerDeploymentCount"
  ): TypedContractMethod<[_o: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getOwnerDeployments"
  ): TypedContractMethod<[_o: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "implementations"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, string, string] & {
        securityToken: string;
        projectNFT: string;
        compliance: string;
        tradeEscrow: string;
        dividendDistributor: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      _admin: AddressLike,
      _securityTokenImpl: AddressLike,
      _projectNFTImpl: AddressLike,
      _complianceImpl: AddressLike,
      _kycVerifier: AddressLike,
      _feeRecipient: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isDeployerApproved"
  ): TypedContractMethod<[_d: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "kycVerifier"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "minKYCLevelForDeployment"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ownerDeployments"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "platformFeeRecipient"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requireApproval"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "requireKYCForDeployment"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "setComplianceImplementation"
  ): TypedContractMethod<[_impl: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDeployerApproval"
  ): TypedContractMethod<[_d: AddressLike, _a: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDividendDistributorImplementation"
  ): TypedContractMethod<[_impl: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setEscrowTransactionFee"
  ): TypedContractMethod<[_feeBps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setKYCRequirement"
  ): TypedContractMethod<[_r: boolean, _l: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setKYCVerifier"
  ): TypedContractMethod<[_v: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPlatformFeeRecipient"
  ): TypedContractMethod<[_r: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setProjectNFTImplementation"
  ): TypedContractMethod<[_impl: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRequireApproval"
  ): TypedContractMethod<[_r: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSecurityTokenImplementation"
  ): TypedContractMethod<[_impl: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTradeEscrowImplementation"
  ): TypedContractMethod<[_impl: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeTo"
  ): TypedContractMethod<
    [newImplementation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getEvent(
    key: "AdminChanged"
  ): TypedContractEvent<
    AdminChangedEvent.InputTuple,
    AdminChangedEvent.OutputTuple,
    AdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "BeaconUpgraded"
  ): TypedContractEvent<
    BeaconUpgradedEvent.InputTuple,
    BeaconUpgradedEvent.OutputTuple,
    BeaconUpgradedEvent.OutputObject
  >;
  getEvent(
    key: "DeployerApprovalUpdated"
  ): TypedContractEvent<
    DeployerApprovalUpdatedEvent.InputTuple,
    DeployerApprovalUpdatedEvent.OutputTuple,
    DeployerApprovalUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "DeploymentDeactivated"
  ): TypedContractEvent<
    DeploymentDeactivatedEvent.InputTuple,
    DeploymentDeactivatedEvent.OutputTuple,
    DeploymentDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "DividendModuleDeployed"
  ): TypedContractEvent<
    DividendModuleDeployedEvent.InputTuple,
    DividendModuleDeployedEvent.OutputTuple,
    DividendModuleDeployedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowDeployed"
  ): TypedContractEvent<
    EscrowDeployedEvent.InputTuple,
    EscrowDeployedEvent.OutputTuple,
    EscrowDeployedEvent.OutputObject
  >;
  getEvent(
    key: "ImplementationUpdated"
  ): TypedContractEvent<
    ImplementationUpdatedEvent.InputTuple,
    ImplementationUpdatedEvent.OutputTuple,
    ImplementationUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "KYCVerifierUpdated"
  ): TypedContractEvent<
    KYCVerifierUpdatedEvent.InputTuple,
    KYCVerifierUpdatedEvent.OutputTuple,
    KYCVerifierUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "ProjectNFTDeployed"
  ): TypedContractEvent<
    ProjectNFTDeployedEvent.InputTuple,
    ProjectNFTDeployedEvent.OutputTuple,
    ProjectNFTDeployedEvent.OutputObject
  >;
  getEvent(
    key: "TokenDeployed"
  ): TypedContractEvent<
    TokenDeployedEvent.InputTuple,
    TokenDeployedEvent.OutputTuple,
    TokenDeployedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "AdminChanged(address,address)": TypedContractEvent<
      AdminChangedEvent.InputTuple,
      AdminChangedEvent.OutputTuple,
      AdminChangedEvent.OutputObject
    >;
    AdminChanged: TypedContractEvent<
      AdminChangedEvent.InputTuple,
      AdminChangedEvent.OutputTuple,
      AdminChangedEvent.OutputObject
    >;

    "BeaconUpgraded(address)": TypedContractEvent<
      BeaconUpgradedEvent.InputTuple,
      BeaconUpgradedEvent.OutputTuple,
      BeaconUpgradedEvent.OutputObject
    >;
    BeaconUpgraded: TypedContractEvent<
      BeaconUpgradedEvent.InputTuple,
      BeaconUpgradedEvent.OutputTuple,
      BeaconUpgradedEvent.OutputObject
    >;

    "DeployerApprovalUpdated(address,bool)": TypedContractEvent<
      DeployerApprovalUpdatedEvent.InputTuple,
      DeployerApprovalUpdatedEvent.OutputTuple,
      DeployerApprovalUpdatedEvent.OutputObject
    >;
    DeployerApprovalUpdated: TypedContractEvent<
      DeployerApprovalUpdatedEvent.InputTuple,
      DeployerApprovalUpdatedEvent.OutputTuple,
      DeployerApprovalUpdatedEvent.OutputObject
    >;

    "DeploymentDeactivated(uint256)": TypedContractEvent<
      DeploymentDeactivatedEvent.InputTuple,
      DeploymentDeactivatedEvent.OutputTuple,
      DeploymentDeactivatedEvent.OutputObject
    >;
    DeploymentDeactivated: TypedContractEvent<
      DeploymentDeactivatedEvent.InputTuple,
      DeploymentDeactivatedEvent.OutputTuple,
      DeploymentDeactivatedEvent.OutputObject
    >;

    "DividendModuleDeployed(uint256,address,address)": TypedContractEvent<
      DividendModuleDeployedEvent.InputTuple,
      DividendModuleDeployedEvent.OutputTuple,
      DividendModuleDeployedEvent.OutputObject
    >;
    DividendModuleDeployed: TypedContractEvent<
      DividendModuleDeployedEvent.InputTuple,
      DividendModuleDeployedEvent.OutputTuple,
      DividendModuleDeployedEvent.OutputObject
    >;

    "EscrowDeployed(uint256,address,address)": TypedContractEvent<
      EscrowDeployedEvent.InputTuple,
      EscrowDeployedEvent.OutputTuple,
      EscrowDeployedEvent.OutputObject
    >;
    EscrowDeployed: TypedContractEvent<
      EscrowDeployedEvent.InputTuple,
      EscrowDeployedEvent.OutputTuple,
      EscrowDeployedEvent.OutputObject
    >;

    "ImplementationUpdated(string,address,address)": TypedContractEvent<
      ImplementationUpdatedEvent.InputTuple,
      ImplementationUpdatedEvent.OutputTuple,
      ImplementationUpdatedEvent.OutputObject
    >;
    ImplementationUpdated: TypedContractEvent<
      ImplementationUpdatedEvent.InputTuple,
      ImplementationUpdatedEvent.OutputTuple,
      ImplementationUpdatedEvent.OutputObject
    >;

    "Initialized(uint8)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "KYCVerifierUpdated(address,address)": TypedContractEvent<
      KYCVerifierUpdatedEvent.InputTuple,
      KYCVerifierUpdatedEvent.OutputTuple,
      KYCVerifierUpdatedEvent.OutputObject
    >;
    KYCVerifierUpdated: TypedContractEvent<
      KYCVerifierUpdatedEvent.InputTuple,
      KYCVerifierUpdatedEvent.OutputTuple,
      KYCVerifierUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "ProjectNFTDeployed(uint256,address,address,uint8)": TypedContractEvent<
      ProjectNFTDeployedEvent.InputTuple,
      ProjectNFTDeployedEvent.OutputTuple,
      ProjectNFTDeployedEvent.OutputObject
    >;
    ProjectNFTDeployed: TypedContractEvent<
      ProjectNFTDeployedEvent.InputTuple,
      ProjectNFTDeployedEvent.OutputTuple,
      ProjectNFTDeployedEvent.OutputObject
    >;

    "TokenDeployed(uint256,address,address,uint256,uint8,uint8)": TypedContractEvent<
      TokenDeployedEvent.InputTuple,
      TokenDeployedEvent.OutputTuple,
      TokenDeployedEvent.OutputObject
    >;
    TokenDeployed: TypedContractEvent<
      TokenDeployedEvent.InputTuple,
      TokenDeployedEvent.OutputTuple,
      TokenDeployedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
