/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ClaimTopicsRegistry__factory } from "./ClaimTopicsRegistry__factory";
export { TrustedIssuersRegistry__factory } from "./TrustedIssuersRegistry__factory";
