/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ClaimTopicsRegistry } from "./ClaimTopicsRegistry";
export type { TrustedIssuersRegistry } from "./TrustedIssuersRegistry";
