/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IRWALaunchpadFactory {
  export type ProjectDeploymentStruct = {
    projectId: BigNumberish;
    securityToken: AddressLike;
    escrowVault: AddressLike;
    compliance: AddressLike;
    deployedAt: BigNumberish;
  };

  export type ProjectDeploymentStructOutput = [
    projectId: bigint,
    securityToken: string,
    escrowVault: string,
    compliance: string,
    deployedAt: bigint
  ] & {
    projectId: bigint;
    securityToken: string;
    escrowVault: string;
    compliance: string;
    deployedAt: bigint;
  };
}

export interface IRWALaunchpadFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "deployProjectContracts"
      | "feeRecipient"
      | "getDeploymentsByOwner"
      | "getProjectDeployment"
      | "identityRegistry"
      | "platformFeeBps"
      | "projectNFT"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "deployProjectContracts",
    values: [
      string,
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "feeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDeploymentsByOwner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProjectDeployment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "identityRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "platformFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "projectNFT",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "deployProjectContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDeploymentsByOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProjectDeployment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "identityRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "platformFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "projectNFT", data: BytesLike): Result;
}

export interface IRWALaunchpadFactory extends BaseContract {
  connect(runner?: ContractRunner | null): IRWALaunchpadFactory;
  waitForDeployment(): Promise<this>;

  interface: IRWALaunchpadFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deployProjectContracts: TypedContractMethod<
    [
      _name: string,
      _symbol: string,
      _metadataURI: string,
      _fundingGoal: BigNumberish,
      _minInvestment: BigNumberish,
      _maxInvestment: BigNumberish,
      _deadline: BigNumberish,
      _maxSupply: BigNumberish,
      _paymentToken: AddressLike
    ],
    [bigint],
    "payable"
  >;

  feeRecipient: TypedContractMethod<[], [string], "view">;

  getDeploymentsByOwner: TypedContractMethod<
    [_owner: AddressLike],
    [bigint[]],
    "view"
  >;

  getProjectDeployment: TypedContractMethod<
    [_projectId: BigNumberish],
    [IRWALaunchpadFactory.ProjectDeploymentStructOutput],
    "view"
  >;

  identityRegistry: TypedContractMethod<[], [string], "view">;

  platformFeeBps: TypedContractMethod<[], [bigint], "view">;

  projectNFT: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deployProjectContracts"
  ): TypedContractMethod<
    [
      _name: string,
      _symbol: string,
      _metadataURI: string,
      _fundingGoal: BigNumberish,
      _minInvestment: BigNumberish,
      _maxInvestment: BigNumberish,
      _deadline: BigNumberish,
      _maxSupply: BigNumberish,
      _paymentToken: AddressLike
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "feeRecipient"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getDeploymentsByOwner"
  ): TypedContractMethod<[_owner: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getProjectDeployment"
  ): TypedContractMethod<
    [_projectId: BigNumberish],
    [IRWALaunchpadFactory.ProjectDeploymentStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "identityRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "projectNFT"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
