/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace KYCManager {
  export type KYCSubmissionStruct = {
    investor: AddressLike;
    level: BigNumberish;
    status: BigNumberish;
    submittedAt: BigNumberish;
    reviewedAt: BigNumberish;
    expiresAt: BigNumberish;
    reviewer: AddressLike;
    documentHash: string;
    countryCode: BigNumberish;
  };

  export type KYCSubmissionStructOutput = [
    investor: string,
    level: bigint,
    status: bigint,
    submittedAt: bigint,
    reviewedAt: bigint,
    expiresAt: bigint,
    reviewer: string,
    documentHash: string,
    countryCode: bigint
  ] & {
    investor: string;
    level: bigint;
    status: bigint;
    submittedAt: bigint;
    reviewedAt: bigint;
    expiresAt: bigint;
    reviewer: string;
    documentHash: string;
    countryCode: bigint;
  };

  export type UpgradeRequestStruct = {
    requestedLevel: BigNumberish;
    documentHash: string;
    submittedAt: BigNumberish;
    pending: boolean;
  };

  export type UpgradeRequestStructOutput = [
    requestedLevel: bigint,
    documentHash: string,
    submittedAt: bigint,
    pending: boolean
  ] & {
    requestedLevel: bigint;
    documentHash: string;
    submittedAt: bigint;
    pending: boolean;
  };
}

export interface KYCManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "REVIEWER_ROLE"
      | "VERIFIER_ROLE"
      | "approveKYC"
      | "approveUpgrade"
      | "authorizedEscrows"
      | "autoRegisterInIdentityRegistry"
      | "autoVerifyThreshold"
      | "blockCountry"
      | "blockedCountries"
      | "canDeployTokens"
      | "canInvest"
      | "feeRecipient"
      | "getContractBalance"
      | "getFeeRecipient"
      | "getInvestmentLimit"
      | "getKYCFee"
      | "getKYCLevel"
      | "getKYCStatus"
      | "getPendingCount"
      | "getPendingSubmissions"
      | "getPendingUpgradeCount"
      | "getPendingUpgrades"
      | "getProjectInvestment"
      | "getRemainingLimit"
      | "getRoleAdmin"
      | "getSubmission"
      | "getTotalFeesCollected"
      | "getTotalInvested"
      | "getUpgradeRequest"
      | "grantRole"
      | "hasRole"
      | "hasUpgradePending"
      | "identityRegistry"
      | "initialize"
      | "isKYCValid"
      | "kycFee"
      | "kycValidityPeriod"
      | "levelInvestmentLimits"
      | "minLevelForIdentityRegistry"
      | "pause"
      | "paused"
      | "projectInvestments"
      | "proxiableUUID"
      | "recordInvestment"
      | "registerIdentityManually"
      | "rejectKYC"
      | "rejectUpgrade"
      | "renounceRole"
      | "requestUpgrade"
      | "resetKYC"
      | "reverseInvestment"
      | "revokeRole"
      | "setAuthorizedEscrow"
      | "setAutoRegisterSettings"
      | "setAutoVerifyThreshold"
      | "setFeeRecipient"
      | "setIdentityRegistry"
      | "setKYCFee"
      | "setKYCValidityPeriod"
      | "setLevelLimit"
      | "submissions"
      | "submitKYC"
      | "supportsInterface"
      | "totalFeesCollected"
      | "totalInvested"
      | "unblockCountry"
      | "unpause"
      | "upgradeRequests"
      | "upgradeTo"
      | "upgradeToAndCall"
      | "withdrawFees"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdminChanged"
      | "AutoRegisterSettingUpdated"
      | "AutoVerified"
      | "BeaconUpgraded"
      | "CountryBlocked"
      | "CountryUnblocked"
      | "EscrowAuthorized"
      | "FeeCollected"
      | "FeeRecipientUpdated"
      | "FeesWithdrawn"
      | "IdentityRegistered"
      | "IdentityRegistryUpdated"
      | "Initialized"
      | "InvestmentRecorded"
      | "InvestmentReversed"
      | "KYCApproved"
      | "KYCExpired"
      | "KYCFeeUpdated"
      | "KYCRejected"
      | "KYCSubmitted"
      | "LevelLimitUpdated"
      | "Paused"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "Unpaused"
      | "UpgradeApproved"
      | "UpgradeRejected"
      | "UpgradeRequested"
      | "Upgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REVIEWER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VERIFIER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approveKYC",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "approveUpgrade",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedEscrows",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "autoRegisterInIdentityRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "autoVerifyThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "blockCountry",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "blockedCountries",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "canDeployTokens",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "canInvest",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "feeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getContractBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFeeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getInvestmentLimit",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "getKYCFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getKYCLevel",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getKYCStatus",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingSubmissions",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingUpgradeCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingUpgrades",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProjectInvestment",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRemainingLimit",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSubmission",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalFeesCollected",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalInvested",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUpgradeRequest",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasUpgradePending",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "identityRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isKYCValid",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "kycFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "kycValidityPeriod",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "levelInvestmentLimits",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "minLevelForIdentityRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "projectInvestments",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recordInvestment",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerIdentityManually",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rejectKYC",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "rejectUpgrade",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestUpgrade",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "resetKYC",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reverseInvestment",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAuthorizedEscrow",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setAutoRegisterSettings",
    values: [boolean, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setAutoVerifyThreshold",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeRecipient",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setIdentityRegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setKYCFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setKYCValidityPeriod",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setLevelLimit",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submissions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitKYC",
    values: [BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalFeesCollected",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalInvested",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unblockCountry",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "upgradeRequests",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeTo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFees",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REVIEWER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VERIFIER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "approveKYC", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "approveUpgrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedEscrows",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "autoRegisterInIdentityRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "autoVerifyThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "blockCountry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "blockedCountries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "canDeployTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "canInvest", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "feeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContractBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getInvestmentLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getKYCFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getKYCLevel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getKYCStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingSubmissions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingUpgradeCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingUpgrades",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProjectInvestment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRemainingLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSubmission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalFeesCollected",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalInvested",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUpgradeRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasUpgradePending",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "identityRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isKYCValid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "kycFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "kycValidityPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "levelInvestmentLimits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minLevelForIdentityRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "projectInvestments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordInvestment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerIdentityManually",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rejectKYC", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rejectUpgrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestUpgrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "resetKYC", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reverseInvestment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAuthorizedEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAutoRegisterSettings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAutoVerifyThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setIdentityRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setKYCFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setKYCValidityPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLevelLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submissions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "submitKYC", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalFeesCollected",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalInvested",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unblockCountry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "upgradeTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFees",
    data: BytesLike
  ): Result;
}

export namespace AdminChangedEvent {
  export type InputTuple = [previousAdmin: AddressLike, newAdmin: AddressLike];
  export type OutputTuple = [previousAdmin: string, newAdmin: string];
  export interface OutputObject {
    previousAdmin: string;
    newAdmin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AutoRegisterSettingUpdatedEvent {
  export type InputTuple = [enabled: boolean, minLevel: BigNumberish];
  export type OutputTuple = [enabled: boolean, minLevel: bigint];
  export interface OutputObject {
    enabled: boolean;
    minLevel: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AutoVerifiedEvent {
  export type InputTuple = [investor: AddressLike, level: BigNumberish];
  export type OutputTuple = [investor: string, level: bigint];
  export interface OutputObject {
    investor: string;
    level: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BeaconUpgradedEvent {
  export type InputTuple = [beacon: AddressLike];
  export type OutputTuple = [beacon: string];
  export interface OutputObject {
    beacon: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CountryBlockedEvent {
  export type InputTuple = [countryCode: BigNumberish];
  export type OutputTuple = [countryCode: bigint];
  export interface OutputObject {
    countryCode: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CountryUnblockedEvent {
  export type InputTuple = [countryCode: BigNumberish];
  export type OutputTuple = [countryCode: bigint];
  export interface OutputObject {
    countryCode: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowAuthorizedEvent {
  export type InputTuple = [escrow: AddressLike, authorized: boolean];
  export type OutputTuple = [escrow: string, authorized: boolean];
  export interface OutputObject {
    escrow: string;
    authorized: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeCollectedEvent {
  export type InputTuple = [investor: AddressLike, amount: BigNumberish];
  export type OutputTuple = [investor: string, amount: bigint];
  export interface OutputObject {
    investor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeRecipientUpdatedEvent {
  export type InputTuple = [
    oldRecipient: AddressLike,
    newRecipient: AddressLike
  ];
  export type OutputTuple = [oldRecipient: string, newRecipient: string];
  export interface OutputObject {
    oldRecipient: string;
    newRecipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeesWithdrawnEvent {
  export type InputTuple = [recipient: AddressLike, amount: BigNumberish];
  export type OutputTuple = [recipient: string, amount: bigint];
  export interface OutputObject {
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IdentityRegisteredEvent {
  export type InputTuple = [investor: AddressLike, countryCode: BigNumberish];
  export type OutputTuple = [investor: string, countryCode: bigint];
  export interface OutputObject {
    investor: string;
    countryCode: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IdentityRegistryUpdatedEvent {
  export type InputTuple = [oldRegistry: AddressLike, newRegistry: AddressLike];
  export type OutputTuple = [oldRegistry: string, newRegistry: string];
  export interface OutputObject {
    oldRegistry: string;
    newRegistry: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InvestmentRecordedEvent {
  export type InputTuple = [
    investor: AddressLike,
    projectId: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    investor: string,
    projectId: bigint,
    amount: bigint
  ];
  export interface OutputObject {
    investor: string;
    projectId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InvestmentReversedEvent {
  export type InputTuple = [
    investor: AddressLike,
    projectId: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    investor: string,
    projectId: bigint,
    amount: bigint
  ];
  export interface OutputObject {
    investor: string;
    projectId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace KYCApprovedEvent {
  export type InputTuple = [
    investor: AddressLike,
    level: BigNumberish,
    reviewer: AddressLike
  ];
  export type OutputTuple = [investor: string, level: bigint, reviewer: string];
  export interface OutputObject {
    investor: string;
    level: bigint;
    reviewer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace KYCExpiredEvent {
  export type InputTuple = [investor: AddressLike];
  export type OutputTuple = [investor: string];
  export interface OutputObject {
    investor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace KYCFeeUpdatedEvent {
  export type InputTuple = [oldFee: BigNumberish, newFee: BigNumberish];
  export type OutputTuple = [oldFee: bigint, newFee: bigint];
  export interface OutputObject {
    oldFee: bigint;
    newFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace KYCRejectedEvent {
  export type InputTuple = [
    investor: AddressLike,
    reviewer: AddressLike,
    reason: string
  ];
  export type OutputTuple = [
    investor: string,
    reviewer: string,
    reason: string
  ];
  export interface OutputObject {
    investor: string;
    reviewer: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace KYCSubmittedEvent {
  export type InputTuple = [
    investor: AddressLike,
    level: BigNumberish,
    documentHash: string
  ];
  export type OutputTuple = [
    investor: string,
    level: bigint,
    documentHash: string
  ];
  export interface OutputObject {
    investor: string;
    level: bigint;
    documentHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LevelLimitUpdatedEvent {
  export type InputTuple = [level: BigNumberish, newLimit: BigNumberish];
  export type OutputTuple = [level: bigint, newLimit: bigint];
  export interface OutputObject {
    level: bigint;
    newLimit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradeApprovedEvent {
  export type InputTuple = [
    investor: AddressLike,
    newLevel: BigNumberish,
    reviewer: AddressLike
  ];
  export type OutputTuple = [
    investor: string,
    newLevel: bigint,
    reviewer: string
  ];
  export interface OutputObject {
    investor: string;
    newLevel: bigint;
    reviewer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradeRejectedEvent {
  export type InputTuple = [
    investor: AddressLike,
    currentLevel: BigNumberish,
    reviewer: AddressLike,
    reason: string
  ];
  export type OutputTuple = [
    investor: string,
    currentLevel: bigint,
    reviewer: string,
    reason: string
  ];
  export interface OutputObject {
    investor: string;
    currentLevel: bigint;
    reviewer: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradeRequestedEvent {
  export type InputTuple = [
    investor: AddressLike,
    fromLevel: BigNumberish,
    toLevel: BigNumberish,
    documentHash: string
  ];
  export type OutputTuple = [
    investor: string,
    fromLevel: bigint,
    toLevel: bigint,
    documentHash: string
  ];
  export interface OutputObject {
    investor: string;
    fromLevel: bigint;
    toLevel: bigint;
    documentHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface KYCManager extends BaseContract {
  connect(runner?: ContractRunner | null): KYCManager;
  waitForDeployment(): Promise<this>;

  interface: KYCManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  REVIEWER_ROLE: TypedContractMethod<[], [string], "view">;

  VERIFIER_ROLE: TypedContractMethod<[], [string], "view">;

  approveKYC: TypedContractMethod<
    [_investor: AddressLike, _approvedLevel: BigNumberish],
    [void],
    "nonpayable"
  >;

  approveUpgrade: TypedContractMethod<
    [_investor: AddressLike],
    [void],
    "nonpayable"
  >;

  authorizedEscrows: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  autoRegisterInIdentityRegistry: TypedContractMethod<[], [boolean], "view">;

  autoVerifyThreshold: TypedContractMethod<[], [bigint], "view">;

  blockCountry: TypedContractMethod<
    [_countryCode: BigNumberish],
    [void],
    "nonpayable"
  >;

  blockedCountries: TypedContractMethod<
    [arg0: BigNumberish],
    [boolean],
    "view"
  >;

  canDeployTokens: TypedContractMethod<
    [_investor: AddressLike],
    [boolean],
    "view"
  >;

  canInvest: TypedContractMethod<
    [_investor: AddressLike, _amount: BigNumberish],
    [boolean],
    "view"
  >;

  feeRecipient: TypedContractMethod<[], [string], "view">;

  getContractBalance: TypedContractMethod<[], [bigint], "view">;

  getFeeRecipient: TypedContractMethod<[], [string], "view">;

  getInvestmentLimit: TypedContractMethod<
    [_investor: AddressLike],
    [bigint],
    "view"
  >;

  getKYCFee: TypedContractMethod<[], [bigint], "view">;

  getKYCLevel: TypedContractMethod<[_investor: AddressLike], [bigint], "view">;

  getKYCStatus: TypedContractMethod<[_investor: AddressLike], [bigint], "view">;

  getPendingCount: TypedContractMethod<[], [bigint], "view">;

  getPendingSubmissions: TypedContractMethod<[], [string[]], "view">;

  getPendingUpgradeCount: TypedContractMethod<[], [bigint], "view">;

  getPendingUpgrades: TypedContractMethod<[], [string[]], "view">;

  getProjectInvestment: TypedContractMethod<
    [_investor: AddressLike, _projectId: BigNumberish],
    [bigint],
    "view"
  >;

  getRemainingLimit: TypedContractMethod<
    [_investor: AddressLike],
    [bigint],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getSubmission: TypedContractMethod<
    [_investor: AddressLike],
    [KYCManager.KYCSubmissionStructOutput],
    "view"
  >;

  getTotalFeesCollected: TypedContractMethod<[], [bigint], "view">;

  getTotalInvested: TypedContractMethod<
    [_investor: AddressLike],
    [bigint],
    "view"
  >;

  getUpgradeRequest: TypedContractMethod<
    [_investor: AddressLike],
    [KYCManager.UpgradeRequestStructOutput],
    "view"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  hasUpgradePending: TypedContractMethod<
    [_investor: AddressLike],
    [boolean],
    "view"
  >;

  identityRegistry: TypedContractMethod<[], [string], "view">;

  initialize: TypedContractMethod<
    [
      _identityRegistry: AddressLike,
      _admin: AddressLike,
      _feeRecipient: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  isKYCValid: TypedContractMethod<[_investor: AddressLike], [boolean], "view">;

  kycFee: TypedContractMethod<[], [bigint], "view">;

  kycValidityPeriod: TypedContractMethod<[], [bigint], "view">;

  levelInvestmentLimits: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  minLevelForIdentityRegistry: TypedContractMethod<[], [bigint], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  projectInvestments: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  recordInvestment: TypedContractMethod<
    [_investor: AddressLike, _projectId: BigNumberish, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  registerIdentityManually: TypedContractMethod<
    [_investor: AddressLike],
    [void],
    "nonpayable"
  >;

  rejectKYC: TypedContractMethod<
    [_investor: AddressLike, _reason: string],
    [void],
    "nonpayable"
  >;

  rejectUpgrade: TypedContractMethod<
    [_investor: AddressLike, _reason: string],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  requestUpgrade: TypedContractMethod<
    [_newLevel: BigNumberish, _documentHash: string],
    [void],
    "payable"
  >;

  resetKYC: TypedContractMethod<[_investor: AddressLike], [void], "nonpayable">;

  reverseInvestment: TypedContractMethod<
    [_investor: AddressLike, _projectId: BigNumberish, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setAuthorizedEscrow: TypedContractMethod<
    [_escrow: AddressLike, _authorized: boolean],
    [void],
    "nonpayable"
  >;

  setAutoRegisterSettings: TypedContractMethod<
    [_enabled: boolean, _minLevel: BigNumberish],
    [void],
    "nonpayable"
  >;

  setAutoVerifyThreshold: TypedContractMethod<
    [_threshold: BigNumberish],
    [void],
    "nonpayable"
  >;

  setFeeRecipient: TypedContractMethod<
    [_newRecipient: AddressLike],
    [void],
    "nonpayable"
  >;

  setIdentityRegistry: TypedContractMethod<
    [_identityRegistry: AddressLike],
    [void],
    "nonpayable"
  >;

  setKYCFee: TypedContractMethod<[_newFee: BigNumberish], [void], "nonpayable">;

  setKYCValidityPeriod: TypedContractMethod<
    [_period: BigNumberish],
    [void],
    "nonpayable"
  >;

  setLevelLimit: TypedContractMethod<
    [_level: BigNumberish, _limit: BigNumberish],
    [void],
    "nonpayable"
  >;

  submissions: TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint
      ] & {
        investor: string;
        level: bigint;
        status: bigint;
        submittedAt: bigint;
        reviewedAt: bigint;
        expiresAt: bigint;
        reviewer: string;
        documentHash: string;
        countryCode: bigint;
      }
    ],
    "view"
  >;

  submitKYC: TypedContractMethod<
    [_level: BigNumberish, _documentHash: string, _countryCode: BigNumberish],
    [void],
    "payable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  totalFeesCollected: TypedContractMethod<[], [bigint], "view">;

  totalInvested: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  unblockCountry: TypedContractMethod<
    [_countryCode: BigNumberish],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  upgradeRequests: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, string, bigint, boolean] & {
        requestedLevel: bigint;
        documentHash: string;
        submittedAt: bigint;
        pending: boolean;
      }
    ],
    "view"
  >;

  upgradeTo: TypedContractMethod<
    [newImplementation: AddressLike],
    [void],
    "nonpayable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  withdrawFees: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "REVIEWER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "VERIFIER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "approveKYC"
  ): TypedContractMethod<
    [_investor: AddressLike, _approvedLevel: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "approveUpgrade"
  ): TypedContractMethod<[_investor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedEscrows"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "autoRegisterInIdentityRegistry"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "autoVerifyThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "blockCountry"
  ): TypedContractMethod<[_countryCode: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "blockedCountries"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "canDeployTokens"
  ): TypedContractMethod<[_investor: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "canInvest"
  ): TypedContractMethod<
    [_investor: AddressLike, _amount: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "feeRecipient"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getContractBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getFeeRecipient"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getInvestmentLimit"
  ): TypedContractMethod<[_investor: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getKYCFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getKYCLevel"
  ): TypedContractMethod<[_investor: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getKYCStatus"
  ): TypedContractMethod<[_investor: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPendingCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPendingSubmissions"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getPendingUpgradeCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPendingUpgrades"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getProjectInvestment"
  ): TypedContractMethod<
    [_investor: AddressLike, _projectId: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRemainingLimit"
  ): TypedContractMethod<[_investor: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getSubmission"
  ): TypedContractMethod<
    [_investor: AddressLike],
    [KYCManager.KYCSubmissionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalFeesCollected"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTotalInvested"
  ): TypedContractMethod<[_investor: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUpgradeRequest"
  ): TypedContractMethod<
    [_investor: AddressLike],
    [KYCManager.UpgradeRequestStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasUpgradePending"
  ): TypedContractMethod<[_investor: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "identityRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      _identityRegistry: AddressLike,
      _admin: AddressLike,
      _feeRecipient: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isKYCValid"
  ): TypedContractMethod<[_investor: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "kycFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "kycValidityPeriod"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "levelInvestmentLimits"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "minLevelForIdentityRegistry"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "projectInvestments"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordInvestment"
  ): TypedContractMethod<
    [_investor: AddressLike, _projectId: BigNumberish, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerIdentityManually"
  ): TypedContractMethod<[_investor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rejectKYC"
  ): TypedContractMethod<
    [_investor: AddressLike, _reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rejectUpgrade"
  ): TypedContractMethod<
    [_investor: AddressLike, _reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestUpgrade"
  ): TypedContractMethod<
    [_newLevel: BigNumberish, _documentHash: string],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "resetKYC"
  ): TypedContractMethod<[_investor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reverseInvestment"
  ): TypedContractMethod<
    [_investor: AddressLike, _projectId: BigNumberish, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAuthorizedEscrow"
  ): TypedContractMethod<
    [_escrow: AddressLike, _authorized: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAutoRegisterSettings"
  ): TypedContractMethod<
    [_enabled: boolean, _minLevel: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAutoVerifyThreshold"
  ): TypedContractMethod<[_threshold: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFeeRecipient"
  ): TypedContractMethod<[_newRecipient: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setIdentityRegistry"
  ): TypedContractMethod<
    [_identityRegistry: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setKYCFee"
  ): TypedContractMethod<[_newFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setKYCValidityPeriod"
  ): TypedContractMethod<[_period: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setLevelLimit"
  ): TypedContractMethod<
    [_level: BigNumberish, _limit: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submissions"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint
      ] & {
        investor: string;
        level: bigint;
        status: bigint;
        submittedAt: bigint;
        reviewedAt: bigint;
        expiresAt: bigint;
        reviewer: string;
        documentHash: string;
        countryCode: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "submitKYC"
  ): TypedContractMethod<
    [_level: BigNumberish, _documentHash: string, _countryCode: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "totalFeesCollected"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalInvested"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "unblockCountry"
  ): TypedContractMethod<[_countryCode: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeRequests"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, string, bigint, boolean] & {
        requestedLevel: bigint;
        documentHash: string;
        submittedAt: bigint;
        pending: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "upgradeTo"
  ): TypedContractMethod<
    [newImplementation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "withdrawFees"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "AdminChanged"
  ): TypedContractEvent<
    AdminChangedEvent.InputTuple,
    AdminChangedEvent.OutputTuple,
    AdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "AutoRegisterSettingUpdated"
  ): TypedContractEvent<
    AutoRegisterSettingUpdatedEvent.InputTuple,
    AutoRegisterSettingUpdatedEvent.OutputTuple,
    AutoRegisterSettingUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "AutoVerified"
  ): TypedContractEvent<
    AutoVerifiedEvent.InputTuple,
    AutoVerifiedEvent.OutputTuple,
    AutoVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "BeaconUpgraded"
  ): TypedContractEvent<
    BeaconUpgradedEvent.InputTuple,
    BeaconUpgradedEvent.OutputTuple,
    BeaconUpgradedEvent.OutputObject
  >;
  getEvent(
    key: "CountryBlocked"
  ): TypedContractEvent<
    CountryBlockedEvent.InputTuple,
    CountryBlockedEvent.OutputTuple,
    CountryBlockedEvent.OutputObject
  >;
  getEvent(
    key: "CountryUnblocked"
  ): TypedContractEvent<
    CountryUnblockedEvent.InputTuple,
    CountryUnblockedEvent.OutputTuple,
    CountryUnblockedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowAuthorized"
  ): TypedContractEvent<
    EscrowAuthorizedEvent.InputTuple,
    EscrowAuthorizedEvent.OutputTuple,
    EscrowAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "FeeCollected"
  ): TypedContractEvent<
    FeeCollectedEvent.InputTuple,
    FeeCollectedEvent.OutputTuple,
    FeeCollectedEvent.OutputObject
  >;
  getEvent(
    key: "FeeRecipientUpdated"
  ): TypedContractEvent<
    FeeRecipientUpdatedEvent.InputTuple,
    FeeRecipientUpdatedEvent.OutputTuple,
    FeeRecipientUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "FeesWithdrawn"
  ): TypedContractEvent<
    FeesWithdrawnEvent.InputTuple,
    FeesWithdrawnEvent.OutputTuple,
    FeesWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "IdentityRegistered"
  ): TypedContractEvent<
    IdentityRegisteredEvent.InputTuple,
    IdentityRegisteredEvent.OutputTuple,
    IdentityRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "IdentityRegistryUpdated"
  ): TypedContractEvent<
    IdentityRegistryUpdatedEvent.InputTuple,
    IdentityRegistryUpdatedEvent.OutputTuple,
    IdentityRegistryUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "InvestmentRecorded"
  ): TypedContractEvent<
    InvestmentRecordedEvent.InputTuple,
    InvestmentRecordedEvent.OutputTuple,
    InvestmentRecordedEvent.OutputObject
  >;
  getEvent(
    key: "InvestmentReversed"
  ): TypedContractEvent<
    InvestmentReversedEvent.InputTuple,
    InvestmentReversedEvent.OutputTuple,
    InvestmentReversedEvent.OutputObject
  >;
  getEvent(
    key: "KYCApproved"
  ): TypedContractEvent<
    KYCApprovedEvent.InputTuple,
    KYCApprovedEvent.OutputTuple,
    KYCApprovedEvent.OutputObject
  >;
  getEvent(
    key: "KYCExpired"
  ): TypedContractEvent<
    KYCExpiredEvent.InputTuple,
    KYCExpiredEvent.OutputTuple,
    KYCExpiredEvent.OutputObject
  >;
  getEvent(
    key: "KYCFeeUpdated"
  ): TypedContractEvent<
    KYCFeeUpdatedEvent.InputTuple,
    KYCFeeUpdatedEvent.OutputTuple,
    KYCFeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "KYCRejected"
  ): TypedContractEvent<
    KYCRejectedEvent.InputTuple,
    KYCRejectedEvent.OutputTuple,
    KYCRejectedEvent.OutputObject
  >;
  getEvent(
    key: "KYCSubmitted"
  ): TypedContractEvent<
    KYCSubmittedEvent.InputTuple,
    KYCSubmittedEvent.OutputTuple,
    KYCSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "LevelLimitUpdated"
  ): TypedContractEvent<
    LevelLimitUpdatedEvent.InputTuple,
    LevelLimitUpdatedEvent.OutputTuple,
    LevelLimitUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "UpgradeApproved"
  ): TypedContractEvent<
    UpgradeApprovedEvent.InputTuple,
    UpgradeApprovedEvent.OutputTuple,
    UpgradeApprovedEvent.OutputObject
  >;
  getEvent(
    key: "UpgradeRejected"
  ): TypedContractEvent<
    UpgradeRejectedEvent.InputTuple,
    UpgradeRejectedEvent.OutputTuple,
    UpgradeRejectedEvent.OutputObject
  >;
  getEvent(
    key: "UpgradeRequested"
  ): TypedContractEvent<
    UpgradeRequestedEvent.InputTuple,
    UpgradeRequestedEvent.OutputTuple,
    UpgradeRequestedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "AdminChanged(address,address)": TypedContractEvent<
      AdminChangedEvent.InputTuple,
      AdminChangedEvent.OutputTuple,
      AdminChangedEvent.OutputObject
    >;
    AdminChanged: TypedContractEvent<
      AdminChangedEvent.InputTuple,
      AdminChangedEvent.OutputTuple,
      AdminChangedEvent.OutputObject
    >;

    "AutoRegisterSettingUpdated(bool,uint8)": TypedContractEvent<
      AutoRegisterSettingUpdatedEvent.InputTuple,
      AutoRegisterSettingUpdatedEvent.OutputTuple,
      AutoRegisterSettingUpdatedEvent.OutputObject
    >;
    AutoRegisterSettingUpdated: TypedContractEvent<
      AutoRegisterSettingUpdatedEvent.InputTuple,
      AutoRegisterSettingUpdatedEvent.OutputTuple,
      AutoRegisterSettingUpdatedEvent.OutputObject
    >;

    "AutoVerified(address,uint8)": TypedContractEvent<
      AutoVerifiedEvent.InputTuple,
      AutoVerifiedEvent.OutputTuple,
      AutoVerifiedEvent.OutputObject
    >;
    AutoVerified: TypedContractEvent<
      AutoVerifiedEvent.InputTuple,
      AutoVerifiedEvent.OutputTuple,
      AutoVerifiedEvent.OutputObject
    >;

    "BeaconUpgraded(address)": TypedContractEvent<
      BeaconUpgradedEvent.InputTuple,
      BeaconUpgradedEvent.OutputTuple,
      BeaconUpgradedEvent.OutputObject
    >;
    BeaconUpgraded: TypedContractEvent<
      BeaconUpgradedEvent.InputTuple,
      BeaconUpgradedEvent.OutputTuple,
      BeaconUpgradedEvent.OutputObject
    >;

    "CountryBlocked(uint16)": TypedContractEvent<
      CountryBlockedEvent.InputTuple,
      CountryBlockedEvent.OutputTuple,
      CountryBlockedEvent.OutputObject
    >;
    CountryBlocked: TypedContractEvent<
      CountryBlockedEvent.InputTuple,
      CountryBlockedEvent.OutputTuple,
      CountryBlockedEvent.OutputObject
    >;

    "CountryUnblocked(uint16)": TypedContractEvent<
      CountryUnblockedEvent.InputTuple,
      CountryUnblockedEvent.OutputTuple,
      CountryUnblockedEvent.OutputObject
    >;
    CountryUnblocked: TypedContractEvent<
      CountryUnblockedEvent.InputTuple,
      CountryUnblockedEvent.OutputTuple,
      CountryUnblockedEvent.OutputObject
    >;

    "EscrowAuthorized(address,bool)": TypedContractEvent<
      EscrowAuthorizedEvent.InputTuple,
      EscrowAuthorizedEvent.OutputTuple,
      EscrowAuthorizedEvent.OutputObject
    >;
    EscrowAuthorized: TypedContractEvent<
      EscrowAuthorizedEvent.InputTuple,
      EscrowAuthorizedEvent.OutputTuple,
      EscrowAuthorizedEvent.OutputObject
    >;

    "FeeCollected(address,uint256)": TypedContractEvent<
      FeeCollectedEvent.InputTuple,
      FeeCollectedEvent.OutputTuple,
      FeeCollectedEvent.OutputObject
    >;
    FeeCollected: TypedContractEvent<
      FeeCollectedEvent.InputTuple,
      FeeCollectedEvent.OutputTuple,
      FeeCollectedEvent.OutputObject
    >;

    "FeeRecipientUpdated(address,address)": TypedContractEvent<
      FeeRecipientUpdatedEvent.InputTuple,
      FeeRecipientUpdatedEvent.OutputTuple,
      FeeRecipientUpdatedEvent.OutputObject
    >;
    FeeRecipientUpdated: TypedContractEvent<
      FeeRecipientUpdatedEvent.InputTuple,
      FeeRecipientUpdatedEvent.OutputTuple,
      FeeRecipientUpdatedEvent.OutputObject
    >;

    "FeesWithdrawn(address,uint256)": TypedContractEvent<
      FeesWithdrawnEvent.InputTuple,
      FeesWithdrawnEvent.OutputTuple,
      FeesWithdrawnEvent.OutputObject
    >;
    FeesWithdrawn: TypedContractEvent<
      FeesWithdrawnEvent.InputTuple,
      FeesWithdrawnEvent.OutputTuple,
      FeesWithdrawnEvent.OutputObject
    >;

    "IdentityRegistered(address,uint16)": TypedContractEvent<
      IdentityRegisteredEvent.InputTuple,
      IdentityRegisteredEvent.OutputTuple,
      IdentityRegisteredEvent.OutputObject
    >;
    IdentityRegistered: TypedContractEvent<
      IdentityRegisteredEvent.InputTuple,
      IdentityRegisteredEvent.OutputTuple,
      IdentityRegisteredEvent.OutputObject
    >;

    "IdentityRegistryUpdated(address,address)": TypedContractEvent<
      IdentityRegistryUpdatedEvent.InputTuple,
      IdentityRegistryUpdatedEvent.OutputTuple,
      IdentityRegistryUpdatedEvent.OutputObject
    >;
    IdentityRegistryUpdated: TypedContractEvent<
      IdentityRegistryUpdatedEvent.InputTuple,
      IdentityRegistryUpdatedEvent.OutputTuple,
      IdentityRegistryUpdatedEvent.OutputObject
    >;

    "Initialized(uint8)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "InvestmentRecorded(address,uint256,uint256)": TypedContractEvent<
      InvestmentRecordedEvent.InputTuple,
      InvestmentRecordedEvent.OutputTuple,
      InvestmentRecordedEvent.OutputObject
    >;
    InvestmentRecorded: TypedContractEvent<
      InvestmentRecordedEvent.InputTuple,
      InvestmentRecordedEvent.OutputTuple,
      InvestmentRecordedEvent.OutputObject
    >;

    "InvestmentReversed(address,uint256,uint256)": TypedContractEvent<
      InvestmentReversedEvent.InputTuple,
      InvestmentReversedEvent.OutputTuple,
      InvestmentReversedEvent.OutputObject
    >;
    InvestmentReversed: TypedContractEvent<
      InvestmentReversedEvent.InputTuple,
      InvestmentReversedEvent.OutputTuple,
      InvestmentReversedEvent.OutputObject
    >;

    "KYCApproved(address,uint8,address)": TypedContractEvent<
      KYCApprovedEvent.InputTuple,
      KYCApprovedEvent.OutputTuple,
      KYCApprovedEvent.OutputObject
    >;
    KYCApproved: TypedContractEvent<
      KYCApprovedEvent.InputTuple,
      KYCApprovedEvent.OutputTuple,
      KYCApprovedEvent.OutputObject
    >;

    "KYCExpired(address)": TypedContractEvent<
      KYCExpiredEvent.InputTuple,
      KYCExpiredEvent.OutputTuple,
      KYCExpiredEvent.OutputObject
    >;
    KYCExpired: TypedContractEvent<
      KYCExpiredEvent.InputTuple,
      KYCExpiredEvent.OutputTuple,
      KYCExpiredEvent.OutputObject
    >;

    "KYCFeeUpdated(uint256,uint256)": TypedContractEvent<
      KYCFeeUpdatedEvent.InputTuple,
      KYCFeeUpdatedEvent.OutputTuple,
      KYCFeeUpdatedEvent.OutputObject
    >;
    KYCFeeUpdated: TypedContractEvent<
      KYCFeeUpdatedEvent.InputTuple,
      KYCFeeUpdatedEvent.OutputTuple,
      KYCFeeUpdatedEvent.OutputObject
    >;

    "KYCRejected(address,address,string)": TypedContractEvent<
      KYCRejectedEvent.InputTuple,
      KYCRejectedEvent.OutputTuple,
      KYCRejectedEvent.OutputObject
    >;
    KYCRejected: TypedContractEvent<
      KYCRejectedEvent.InputTuple,
      KYCRejectedEvent.OutputTuple,
      KYCRejectedEvent.OutputObject
    >;

    "KYCSubmitted(address,uint8,string)": TypedContractEvent<
      KYCSubmittedEvent.InputTuple,
      KYCSubmittedEvent.OutputTuple,
      KYCSubmittedEvent.OutputObject
    >;
    KYCSubmitted: TypedContractEvent<
      KYCSubmittedEvent.InputTuple,
      KYCSubmittedEvent.OutputTuple,
      KYCSubmittedEvent.OutputObject
    >;

    "LevelLimitUpdated(uint8,uint256)": TypedContractEvent<
      LevelLimitUpdatedEvent.InputTuple,
      LevelLimitUpdatedEvent.OutputTuple,
      LevelLimitUpdatedEvent.OutputObject
    >;
    LevelLimitUpdated: TypedContractEvent<
      LevelLimitUpdatedEvent.InputTuple,
      LevelLimitUpdatedEvent.OutputTuple,
      LevelLimitUpdatedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "UpgradeApproved(address,uint8,address)": TypedContractEvent<
      UpgradeApprovedEvent.InputTuple,
      UpgradeApprovedEvent.OutputTuple,
      UpgradeApprovedEvent.OutputObject
    >;
    UpgradeApproved: TypedContractEvent<
      UpgradeApprovedEvent.InputTuple,
      UpgradeApprovedEvent.OutputTuple,
      UpgradeApprovedEvent.OutputObject
    >;

    "UpgradeRejected(address,uint8,address,string)": TypedContractEvent<
      UpgradeRejectedEvent.InputTuple,
      UpgradeRejectedEvent.OutputTuple,
      UpgradeRejectedEvent.OutputObject
    >;
    UpgradeRejected: TypedContractEvent<
      UpgradeRejectedEvent.InputTuple,
      UpgradeRejectedEvent.OutputTuple,
      UpgradeRejectedEvent.OutputObject
    >;

    "UpgradeRequested(address,uint8,uint8,string)": TypedContractEvent<
      UpgradeRequestedEvent.InputTuple,
      UpgradeRequestedEvent.OutputTuple,
      UpgradeRequestedEvent.OutputObject
    >;
    UpgradeRequested: TypedContractEvent<
      UpgradeRequestedEvent.InputTuple,
      UpgradeRequestedEvent.OutputTuple,
      UpgradeRequestedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
