/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace RWASecurityExchange {
  export type KYCProofStruct = {
    level: BigNumberish;
    countryCode: BigNumberish;
    expiry: BigNumberish;
    signature: BytesLike;
  };

  export type KYCProofStructOutput = [
    level: bigint,
    countryCode: bigint,
    expiry: bigint,
    signature: string
  ] & { level: bigint; countryCode: bigint; expiry: bigint; signature: string };

  export type OrderStruct = {
    id: BigNumberish;
    trader: AddressLike;
    securityToken: AddressLike;
    paymentToken: AddressLike;
    side: BigNumberish;
    price: BigNumberish;
    amount: BigNumberish;
    filled: BigNumberish;
    createdAt: BigNumberish;
    status: BigNumberish;
  };

  export type OrderStructOutput = [
    id: bigint,
    trader: string,
    securityToken: string,
    paymentToken: string,
    side: bigint,
    price: bigint,
    amount: bigint,
    filled: bigint,
    createdAt: bigint,
    status: bigint
  ] & {
    id: bigint;
    trader: string;
    securityToken: string;
    paymentToken: string;
    side: bigint;
    price: bigint;
    amount: bigint;
    filled: bigint;
    createdAt: bigint;
    status: bigint;
  };

  export type TradeStruct = {
    id: BigNumberish;
    buyOrderId: BigNumberish;
    sellOrderId: BigNumberish;
    buyer: AddressLike;
    seller: AddressLike;
    securityToken: AddressLike;
    paymentToken: AddressLike;
    price: BigNumberish;
    amount: BigNumberish;
    timestamp: BigNumberish;
  };

  export type TradeStructOutput = [
    id: bigint,
    buyOrderId: bigint,
    sellOrderId: bigint,
    buyer: string,
    seller: string,
    securityToken: string,
    paymentToken: string,
    price: bigint,
    amount: bigint,
    timestamp: bigint
  ] & {
    id: bigint;
    buyOrderId: bigint;
    sellOrderId: bigint;
    buyer: string;
    seller: string;
    securityToken: string;
    paymentToken: string;
    price: bigint;
    amount: bigint;
    timestamp: bigint;
  };

  export type TradingPairStruct = {
    securityToken: AddressLike;
    paymentToken: AddressLike;
    active: boolean;
    lastPrice: BigNumberish;
    totalVolume: BigNumberish;
    tradesCount: BigNumberish;
    createdAt: BigNumberish;
    minKYCLevel: BigNumberish;
  };

  export type TradingPairStructOutput = [
    securityToken: string,
    paymentToken: string,
    active: boolean,
    lastPrice: bigint,
    totalVolume: bigint,
    tradesCount: bigint,
    createdAt: bigint,
    minKYCLevel: bigint
  ] & {
    securityToken: string;
    paymentToken: string;
    active: boolean;
    lastPrice: bigint;
    totalVolume: bigint;
    tradesCount: bigint;
    createdAt: bigint;
    minKYCLevel: bigint;
  };
}

export interface RWASecurityExchangeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "FACTORY_ROLE"
      | "OPERATOR_ROLE"
      | "UPGRADER_ROLE"
      | "acceptedPaymentTokens"
      | "addDefaultRestrictedCountry"
      | "autoCreatePairs"
      | "batchSetPairCountryRestrictions"
      | "buyOrderBook"
      | "cancelOrder"
      | "createOrder"
      | "createPairForToken"
      | "createPairsForToken"
      | "createTradingPair"
      | "createTradingPairWithKYCLevel"
      | "defaultMinKYCLevel"
      | "defaultPaymentToken"
      | "defaultRestrictedCountries"
      | "emergencyWithdraw"
      | "feeCollector"
      | "getDefaultRestrictedCountries"
      | "getKYCVerifier"
      | "getOrder"
      | "getOrderBook"
      | "getPairId"
      | "getPairTrades"
      | "getRoleAdmin"
      | "getTotalOrders"
      | "getTotalTrades"
      | "getTrade"
      | "getTradingPair"
      | "getUserActiveOrders"
      | "getUserOrders"
      | "grantRole"
      | "hasRole"
      | "initialize"
      | "isCountryRestricted"
      | "kycVerifier"
      | "makerFeeBps"
      | "orders"
      | "pairRestrictedCountries"
      | "pairTrades"
      | "pause"
      | "paused"
      | "proxiableUUID"
      | "removeDefaultRestrictedCountry"
      | "renounceRole"
      | "revokeRole"
      | "sellOrderBook"
      | "setAcceptedPaymentToken"
      | "setAutoCreatePairs"
      | "setDefaultMinKYCLevel"
      | "setDefaultPaymentToken"
      | "setFeeCollector"
      | "setFees"
      | "setKYCVerifier"
      | "setPairCountryRestriction"
      | "setTradingPairKYCLevel"
      | "setTradingPairStatus"
      | "supportsInterface"
      | "takerFeeBps"
      | "trades"
      | "tradingPairs"
      | "unpause"
      | "upgradeTo"
      | "upgradeToAndCall"
      | "userOrders"
      | "validPairs"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdminChanged"
      | "BeaconUpgraded"
      | "DefaultMinKYCLevelUpdated"
      | "DefaultRestrictedCountryUpdated"
      | "FeeCollectorUpdated"
      | "FeesUpdated"
      | "Initialized"
      | "KYCVerifierUpdated"
      | "OrderCancelled"
      | "OrderCreated"
      | "OrderFilled"
      | "PairCountryRestrictionUpdated"
      | "Paused"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "TradeExecuted"
      | "TradingPairCreated"
      | "TradingPairKYCLevelChanged"
      | "TradingPairStatusChanged"
      | "Unpaused"
      | "Upgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FACTORY_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "OPERATOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UPGRADER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptedPaymentTokens",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addDefaultRestrictedCountry",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "autoCreatePairs",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "batchSetPairCountryRestrictions",
    values: [BytesLike, BigNumberish[], boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "buyOrderBook",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createOrder",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      RWASecurityExchange.KYCProofStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createPairForToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createPairsForToken",
    values: [AddressLike, AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "createTradingPair",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createTradingPairWithKYCLevel",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "defaultMinKYCLevel",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "defaultPaymentToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "defaultRestrictedCountries",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "feeCollector",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDefaultRestrictedCountries",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getKYCVerifier",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOrderBook",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPairId",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPairTrades",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalOrders",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalTrades",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTrade",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTradingPair",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserActiveOrders",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserOrders",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isCountryRestricted",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "kycVerifier",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "makerFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "orders",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pairRestrictedCountries",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pairTrades",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeDefaultRestrictedCountry",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sellOrderBook",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setAcceptedPaymentToken",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setAutoCreatePairs",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setDefaultMinKYCLevel",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDefaultPaymentToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeCollector",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFees",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setKYCVerifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPairCountryRestriction",
    values: [BytesLike, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setTradingPairKYCLevel",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTradingPairStatus",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "takerFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "trades",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tradingPairs",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "upgradeTo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userOrders",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "validPairs",
    values: [AddressLike, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FACTORY_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "OPERATOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UPGRADER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptedPaymentTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addDefaultRestrictedCountry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "autoCreatePairs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchSetPairCountryRestrictions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "buyOrderBook",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createPairForToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createPairsForToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createTradingPair",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createTradingPairWithKYCLevel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "defaultMinKYCLevel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "defaultPaymentToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "defaultRestrictedCountries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeCollector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDefaultRestrictedCountries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getKYCVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getOrder", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getOrderBook",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPairId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPairTrades",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalTrades",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTrade", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTradingPair",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserActiveOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isCountryRestricted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "kycVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "makerFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "orders", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pairRestrictedCountries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pairTrades", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeDefaultRestrictedCountry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sellOrderBook",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAcceptedPaymentToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAutoCreatePairs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDefaultMinKYCLevel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDefaultPaymentToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeCollector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFees", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setKYCVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPairCountryRestriction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTradingPairKYCLevel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTradingPairStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "takerFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "trades", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tradingPairs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "upgradeTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userOrders", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "validPairs", data: BytesLike): Result;
}

export namespace AdminChangedEvent {
  export type InputTuple = [previousAdmin: AddressLike, newAdmin: AddressLike];
  export type OutputTuple = [previousAdmin: string, newAdmin: string];
  export interface OutputObject {
    previousAdmin: string;
    newAdmin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BeaconUpgradedEvent {
  export type InputTuple = [beacon: AddressLike];
  export type OutputTuple = [beacon: string];
  export interface OutputObject {
    beacon: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DefaultMinKYCLevelUpdatedEvent {
  export type InputTuple = [oldLevel: BigNumberish, newLevel: BigNumberish];
  export type OutputTuple = [oldLevel: bigint, newLevel: bigint];
  export interface OutputObject {
    oldLevel: bigint;
    newLevel: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DefaultRestrictedCountryUpdatedEvent {
  export type InputTuple = [countryCode: BigNumberish, restricted: boolean];
  export type OutputTuple = [countryCode: bigint, restricted: boolean];
  export interface OutputObject {
    countryCode: bigint;
    restricted: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeCollectorUpdatedEvent {
  export type InputTuple = [newCollector: AddressLike];
  export type OutputTuple = [newCollector: string];
  export interface OutputObject {
    newCollector: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeesUpdatedEvent {
  export type InputTuple = [
    makerFeeBps: BigNumberish,
    takerFeeBps: BigNumberish
  ];
  export type OutputTuple = [makerFeeBps: bigint, takerFeeBps: bigint];
  export interface OutputObject {
    makerFeeBps: bigint;
    takerFeeBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace KYCVerifierUpdatedEvent {
  export type InputTuple = [oldVerifier: AddressLike, newVerifier: AddressLike];
  export type OutputTuple = [oldVerifier: string, newVerifier: string];
  export interface OutputObject {
    oldVerifier: string;
    newVerifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderCancelledEvent {
  export type InputTuple = [orderId: BigNumberish];
  export type OutputTuple = [orderId: bigint];
  export interface OutputObject {
    orderId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderCreatedEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    trader: AddressLike,
    securityToken: AddressLike,
    paymentToken: AddressLike,
    side: BigNumberish,
    price: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    orderId: bigint,
    trader: string,
    securityToken: string,
    paymentToken: string,
    side: bigint,
    price: bigint,
    amount: bigint
  ];
  export interface OutputObject {
    orderId: bigint;
    trader: string;
    securityToken: string;
    paymentToken: string;
    side: bigint;
    price: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderFilledEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    filledAmount: BigNumberish,
    remainingAmount: BigNumberish
  ];
  export type OutputTuple = [
    orderId: bigint,
    filledAmount: bigint,
    remainingAmount: bigint
  ];
  export interface OutputObject {
    orderId: bigint;
    filledAmount: bigint;
    remainingAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PairCountryRestrictionUpdatedEvent {
  export type InputTuple = [
    pairId: BytesLike,
    countryCode: BigNumberish,
    restricted: boolean
  ];
  export type OutputTuple = [
    pairId: string,
    countryCode: bigint,
    restricted: boolean
  ];
  export interface OutputObject {
    pairId: string;
    countryCode: bigint;
    restricted: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradeExecutedEvent {
  export type InputTuple = [
    tradeId: BigNumberish,
    buyOrderId: BigNumberish,
    sellOrderId: BigNumberish,
    buyer: AddressLike,
    seller: AddressLike,
    price: BigNumberish,
    amount: BigNumberish,
    buyerFee: BigNumberish,
    sellerFee: BigNumberish
  ];
  export type OutputTuple = [
    tradeId: bigint,
    buyOrderId: bigint,
    sellOrderId: bigint,
    buyer: string,
    seller: string,
    price: bigint,
    amount: bigint,
    buyerFee: bigint,
    sellerFee: bigint
  ];
  export interface OutputObject {
    tradeId: bigint;
    buyOrderId: bigint;
    sellOrderId: bigint;
    buyer: string;
    seller: string;
    price: bigint;
    amount: bigint;
    buyerFee: bigint;
    sellerFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradingPairCreatedEvent {
  export type InputTuple = [
    securityToken: AddressLike,
    paymentToken: AddressLike,
    pairId: BytesLike,
    minKYCLevel: BigNumberish
  ];
  export type OutputTuple = [
    securityToken: string,
    paymentToken: string,
    pairId: string,
    minKYCLevel: bigint
  ];
  export interface OutputObject {
    securityToken: string;
    paymentToken: string;
    pairId: string;
    minKYCLevel: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradingPairKYCLevelChangedEvent {
  export type InputTuple = [
    pairId: BytesLike,
    oldLevel: BigNumberish,
    newLevel: BigNumberish
  ];
  export type OutputTuple = [
    pairId: string,
    oldLevel: bigint,
    newLevel: bigint
  ];
  export interface OutputObject {
    pairId: string;
    oldLevel: bigint;
    newLevel: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradingPairStatusChangedEvent {
  export type InputTuple = [pairId: BytesLike, active: boolean];
  export type OutputTuple = [pairId: string, active: boolean];
  export interface OutputObject {
    pairId: string;
    active: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RWASecurityExchange extends BaseContract {
  connect(runner?: ContractRunner | null): RWASecurityExchange;
  waitForDeployment(): Promise<this>;

  interface: RWASecurityExchangeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  FACTORY_ROLE: TypedContractMethod<[], [string], "view">;

  OPERATOR_ROLE: TypedContractMethod<[], [string], "view">;

  UPGRADER_ROLE: TypedContractMethod<[], [string], "view">;

  acceptedPaymentTokens: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  addDefaultRestrictedCountry: TypedContractMethod<
    [_countryCode: BigNumberish],
    [void],
    "nonpayable"
  >;

  autoCreatePairs: TypedContractMethod<[], [boolean], "view">;

  batchSetPairCountryRestrictions: TypedContractMethod<
    [_pairId: BytesLike, _countryCodes: BigNumberish[], _restricted: boolean],
    [void],
    "nonpayable"
  >;

  buyOrderBook: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  cancelOrder: TypedContractMethod<
    [_orderId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createOrder: TypedContractMethod<
    [
      _securityToken: AddressLike,
      _paymentToken: AddressLike,
      _side: BigNumberish,
      _price: BigNumberish,
      _amount: BigNumberish,
      _kycProof: RWASecurityExchange.KYCProofStruct
    ],
    [bigint],
    "nonpayable"
  >;

  createPairForToken: TypedContractMethod<
    [_securityToken: AddressLike],
    [string],
    "nonpayable"
  >;

  createPairsForToken: TypedContractMethod<
    [_securityToken: AddressLike, _paymentTokens: AddressLike[]],
    [void],
    "nonpayable"
  >;

  createTradingPair: TypedContractMethod<
    [_securityToken: AddressLike, _paymentToken: AddressLike],
    [string],
    "nonpayable"
  >;

  createTradingPairWithKYCLevel: TypedContractMethod<
    [
      _securityToken: AddressLike,
      _paymentToken: AddressLike,
      _minKYCLevel: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  defaultMinKYCLevel: TypedContractMethod<[], [bigint], "view">;

  defaultPaymentToken: TypedContractMethod<[], [string], "view">;

  defaultRestrictedCountries: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  emergencyWithdraw: TypedContractMethod<
    [_token: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  feeCollector: TypedContractMethod<[], [string], "view">;

  getDefaultRestrictedCountries: TypedContractMethod<[], [bigint[]], "view">;

  getKYCVerifier: TypedContractMethod<[], [string], "view">;

  getOrder: TypedContractMethod<
    [_orderId: BigNumberish],
    [RWASecurityExchange.OrderStructOutput],
    "view"
  >;

  getOrderBook: TypedContractMethod<
    [
      _securityToken: AddressLike,
      _paymentToken: AddressLike,
      _limit: BigNumberish
    ],
    [
      [
        RWASecurityExchange.OrderStructOutput[],
        RWASecurityExchange.OrderStructOutput[]
      ] & {
        buyOrders: RWASecurityExchange.OrderStructOutput[];
        sellOrders: RWASecurityExchange.OrderStructOutput[];
      }
    ],
    "view"
  >;

  getPairId: TypedContractMethod<
    [_securityToken: AddressLike, _paymentToken: AddressLike],
    [string],
    "view"
  >;

  getPairTrades: TypedContractMethod<
    [_pairId: BytesLike, _limit: BigNumberish],
    [RWASecurityExchange.TradeStructOutput[]],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getTotalOrders: TypedContractMethod<[], [bigint], "view">;

  getTotalTrades: TypedContractMethod<[], [bigint], "view">;

  getTrade: TypedContractMethod<
    [_tradeId: BigNumberish],
    [RWASecurityExchange.TradeStructOutput],
    "view"
  >;

  getTradingPair: TypedContractMethod<
    [_securityToken: AddressLike, _paymentToken: AddressLike],
    [RWASecurityExchange.TradingPairStructOutput],
    "view"
  >;

  getUserActiveOrders: TypedContractMethod<
    [_user: AddressLike],
    [RWASecurityExchange.OrderStructOutput[]],
    "view"
  >;

  getUserOrders: TypedContractMethod<[_user: AddressLike], [bigint[]], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  initialize: TypedContractMethod<
    [
      _admin: AddressLike,
      _kycVerifier: AddressLike,
      _defaultPaymentToken: AddressLike,
      _feeCollector: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  isCountryRestricted: TypedContractMethod<
    [_countryCode: BigNumberish, _pairId: BytesLike],
    [boolean],
    "view"
  >;

  kycVerifier: TypedContractMethod<[], [string], "view">;

  makerFeeBps: TypedContractMethod<[], [bigint], "view">;

  orders: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        trader: string;
        securityToken: string;
        paymentToken: string;
        side: bigint;
        price: bigint;
        amount: bigint;
        filled: bigint;
        createdAt: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  pairRestrictedCountries: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  pairTrades: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  removeDefaultRestrictedCountry: TypedContractMethod<
    [_countryCode: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  sellOrderBook: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  setAcceptedPaymentToken: TypedContractMethod<
    [_token: AddressLike, _accepted: boolean],
    [void],
    "nonpayable"
  >;

  setAutoCreatePairs: TypedContractMethod<
    [_enabled: boolean],
    [void],
    "nonpayable"
  >;

  setDefaultMinKYCLevel: TypedContractMethod<
    [_level: BigNumberish],
    [void],
    "nonpayable"
  >;

  setDefaultPaymentToken: TypedContractMethod<
    [_token: AddressLike],
    [void],
    "nonpayable"
  >;

  setFeeCollector: TypedContractMethod<
    [_feeCollector: AddressLike],
    [void],
    "nonpayable"
  >;

  setFees: TypedContractMethod<
    [_makerFeeBps: BigNumberish, _takerFeeBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  setKYCVerifier: TypedContractMethod<
    [_kycVerifier: AddressLike],
    [void],
    "nonpayable"
  >;

  setPairCountryRestriction: TypedContractMethod<
    [_pairId: BytesLike, _countryCode: BigNumberish, _restricted: boolean],
    [void],
    "nonpayable"
  >;

  setTradingPairKYCLevel: TypedContractMethod<
    [_pairId: BytesLike, _minKYCLevel: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTradingPairStatus: TypedContractMethod<
    [_pairId: BytesLike, _active: boolean],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  takerFeeBps: TypedContractMethod<[], [bigint], "view">;

  trades: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        buyOrderId: bigint;
        sellOrderId: bigint;
        buyer: string;
        seller: string;
        securityToken: string;
        paymentToken: string;
        price: bigint;
        amount: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  tradingPairs: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, boolean, bigint, bigint, bigint, bigint, bigint] & {
        securityToken: string;
        paymentToken: string;
        active: boolean;
        lastPrice: bigint;
        totalVolume: bigint;
        tradesCount: bigint;
        createdAt: bigint;
        minKYCLevel: bigint;
      }
    ],
    "view"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  upgradeTo: TypedContractMethod<
    [newImplementation: AddressLike],
    [void],
    "nonpayable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  userOrders: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  validPairs: TypedContractMethod<
    [_securityToken: AddressLike, _paymentToken: AddressLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "FACTORY_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "OPERATOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "UPGRADER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "acceptedPaymentTokens"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "addDefaultRestrictedCountry"
  ): TypedContractMethod<[_countryCode: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "autoCreatePairs"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "batchSetPairCountryRestrictions"
  ): TypedContractMethod<
    [_pairId: BytesLike, _countryCodes: BigNumberish[], _restricted: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "buyOrderBook"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancelOrder"
  ): TypedContractMethod<[_orderId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createOrder"
  ): TypedContractMethod<
    [
      _securityToken: AddressLike,
      _paymentToken: AddressLike,
      _side: BigNumberish,
      _price: BigNumberish,
      _amount: BigNumberish,
      _kycProof: RWASecurityExchange.KYCProofStruct
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createPairForToken"
  ): TypedContractMethod<[_securityToken: AddressLike], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "createPairsForToken"
  ): TypedContractMethod<
    [_securityToken: AddressLike, _paymentTokens: AddressLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createTradingPair"
  ): TypedContractMethod<
    [_securityToken: AddressLike, _paymentToken: AddressLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createTradingPairWithKYCLevel"
  ): TypedContractMethod<
    [
      _securityToken: AddressLike,
      _paymentToken: AddressLike,
      _minKYCLevel: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "defaultMinKYCLevel"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "defaultPaymentToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "defaultRestrictedCountries"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<
    [_token: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "feeCollector"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getDefaultRestrictedCountries"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getKYCVerifier"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getOrder"
  ): TypedContractMethod<
    [_orderId: BigNumberish],
    [RWASecurityExchange.OrderStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOrderBook"
  ): TypedContractMethod<
    [
      _securityToken: AddressLike,
      _paymentToken: AddressLike,
      _limit: BigNumberish
    ],
    [
      [
        RWASecurityExchange.OrderStructOutput[],
        RWASecurityExchange.OrderStructOutput[]
      ] & {
        buyOrders: RWASecurityExchange.OrderStructOutput[];
        sellOrders: RWASecurityExchange.OrderStructOutput[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPairId"
  ): TypedContractMethod<
    [_securityToken: AddressLike, _paymentToken: AddressLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPairTrades"
  ): TypedContractMethod<
    [_pairId: BytesLike, _limit: BigNumberish],
    [RWASecurityExchange.TradeStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getTotalOrders"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTotalTrades"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTrade"
  ): TypedContractMethod<
    [_tradeId: BigNumberish],
    [RWASecurityExchange.TradeStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTradingPair"
  ): TypedContractMethod<
    [_securityToken: AddressLike, _paymentToken: AddressLike],
    [RWASecurityExchange.TradingPairStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserActiveOrders"
  ): TypedContractMethod<
    [_user: AddressLike],
    [RWASecurityExchange.OrderStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserOrders"
  ): TypedContractMethod<[_user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      _admin: AddressLike,
      _kycVerifier: AddressLike,
      _defaultPaymentToken: AddressLike,
      _feeCollector: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isCountryRestricted"
  ): TypedContractMethod<
    [_countryCode: BigNumberish, _pairId: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "kycVerifier"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "makerFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "orders"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        trader: string;
        securityToken: string;
        paymentToken: string;
        side: bigint;
        price: bigint;
        amount: bigint;
        filled: bigint;
        createdAt: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "pairRestrictedCountries"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "pairTrades"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeDefaultRestrictedCountry"
  ): TypedContractMethod<[_countryCode: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sellOrderBook"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "setAcceptedPaymentToken"
  ): TypedContractMethod<
    [_token: AddressLike, _accepted: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAutoCreatePairs"
  ): TypedContractMethod<[_enabled: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDefaultMinKYCLevel"
  ): TypedContractMethod<[_level: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDefaultPaymentToken"
  ): TypedContractMethod<[_token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFeeCollector"
  ): TypedContractMethod<[_feeCollector: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFees"
  ): TypedContractMethod<
    [_makerFeeBps: BigNumberish, _takerFeeBps: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setKYCVerifier"
  ): TypedContractMethod<[_kycVerifier: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPairCountryRestriction"
  ): TypedContractMethod<
    [_pairId: BytesLike, _countryCode: BigNumberish, _restricted: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTradingPairKYCLevel"
  ): TypedContractMethod<
    [_pairId: BytesLike, _minKYCLevel: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTradingPairStatus"
  ): TypedContractMethod<
    [_pairId: BytesLike, _active: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "takerFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "trades"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        buyOrderId: bigint;
        sellOrderId: bigint;
        buyer: string;
        seller: string;
        securityToken: string;
        paymentToken: string;
        price: bigint;
        amount: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "tradingPairs"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, boolean, bigint, bigint, bigint, bigint, bigint] & {
        securityToken: string;
        paymentToken: string;
        active: boolean;
        lastPrice: bigint;
        totalVolume: bigint;
        tradesCount: bigint;
        createdAt: bigint;
        minKYCLevel: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeTo"
  ): TypedContractMethod<
    [newImplementation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "userOrders"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "validPairs"
  ): TypedContractMethod<
    [_securityToken: AddressLike, _paymentToken: AddressLike],
    [boolean],
    "view"
  >;

  getEvent(
    key: "AdminChanged"
  ): TypedContractEvent<
    AdminChangedEvent.InputTuple,
    AdminChangedEvent.OutputTuple,
    AdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "BeaconUpgraded"
  ): TypedContractEvent<
    BeaconUpgradedEvent.InputTuple,
    BeaconUpgradedEvent.OutputTuple,
    BeaconUpgradedEvent.OutputObject
  >;
  getEvent(
    key: "DefaultMinKYCLevelUpdated"
  ): TypedContractEvent<
    DefaultMinKYCLevelUpdatedEvent.InputTuple,
    DefaultMinKYCLevelUpdatedEvent.OutputTuple,
    DefaultMinKYCLevelUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "DefaultRestrictedCountryUpdated"
  ): TypedContractEvent<
    DefaultRestrictedCountryUpdatedEvent.InputTuple,
    DefaultRestrictedCountryUpdatedEvent.OutputTuple,
    DefaultRestrictedCountryUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "FeeCollectorUpdated"
  ): TypedContractEvent<
    FeeCollectorUpdatedEvent.InputTuple,
    FeeCollectorUpdatedEvent.OutputTuple,
    FeeCollectorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "FeesUpdated"
  ): TypedContractEvent<
    FeesUpdatedEvent.InputTuple,
    FeesUpdatedEvent.OutputTuple,
    FeesUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "KYCVerifierUpdated"
  ): TypedContractEvent<
    KYCVerifierUpdatedEvent.InputTuple,
    KYCVerifierUpdatedEvent.OutputTuple,
    KYCVerifierUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OrderCancelled"
  ): TypedContractEvent<
    OrderCancelledEvent.InputTuple,
    OrderCancelledEvent.OutputTuple,
    OrderCancelledEvent.OutputObject
  >;
  getEvent(
    key: "OrderCreated"
  ): TypedContractEvent<
    OrderCreatedEvent.InputTuple,
    OrderCreatedEvent.OutputTuple,
    OrderCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OrderFilled"
  ): TypedContractEvent<
    OrderFilledEvent.InputTuple,
    OrderFilledEvent.OutputTuple,
    OrderFilledEvent.OutputObject
  >;
  getEvent(
    key: "PairCountryRestrictionUpdated"
  ): TypedContractEvent<
    PairCountryRestrictionUpdatedEvent.InputTuple,
    PairCountryRestrictionUpdatedEvent.OutputTuple,
    PairCountryRestrictionUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "TradeExecuted"
  ): TypedContractEvent<
    TradeExecutedEvent.InputTuple,
    TradeExecutedEvent.OutputTuple,
    TradeExecutedEvent.OutputObject
  >;
  getEvent(
    key: "TradingPairCreated"
  ): TypedContractEvent<
    TradingPairCreatedEvent.InputTuple,
    TradingPairCreatedEvent.OutputTuple,
    TradingPairCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TradingPairKYCLevelChanged"
  ): TypedContractEvent<
    TradingPairKYCLevelChangedEvent.InputTuple,
    TradingPairKYCLevelChangedEvent.OutputTuple,
    TradingPairKYCLevelChangedEvent.OutputObject
  >;
  getEvent(
    key: "TradingPairStatusChanged"
  ): TypedContractEvent<
    TradingPairStatusChangedEvent.InputTuple,
    TradingPairStatusChangedEvent.OutputTuple,
    TradingPairStatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "AdminChanged(address,address)": TypedContractEvent<
      AdminChangedEvent.InputTuple,
      AdminChangedEvent.OutputTuple,
      AdminChangedEvent.OutputObject
    >;
    AdminChanged: TypedContractEvent<
      AdminChangedEvent.InputTuple,
      AdminChangedEvent.OutputTuple,
      AdminChangedEvent.OutputObject
    >;

    "BeaconUpgraded(address)": TypedContractEvent<
      BeaconUpgradedEvent.InputTuple,
      BeaconUpgradedEvent.OutputTuple,
      BeaconUpgradedEvent.OutputObject
    >;
    BeaconUpgraded: TypedContractEvent<
      BeaconUpgradedEvent.InputTuple,
      BeaconUpgradedEvent.OutputTuple,
      BeaconUpgradedEvent.OutputObject
    >;

    "DefaultMinKYCLevelUpdated(uint8,uint8)": TypedContractEvent<
      DefaultMinKYCLevelUpdatedEvent.InputTuple,
      DefaultMinKYCLevelUpdatedEvent.OutputTuple,
      DefaultMinKYCLevelUpdatedEvent.OutputObject
    >;
    DefaultMinKYCLevelUpdated: TypedContractEvent<
      DefaultMinKYCLevelUpdatedEvent.InputTuple,
      DefaultMinKYCLevelUpdatedEvent.OutputTuple,
      DefaultMinKYCLevelUpdatedEvent.OutputObject
    >;

    "DefaultRestrictedCountryUpdated(uint16,bool)": TypedContractEvent<
      DefaultRestrictedCountryUpdatedEvent.InputTuple,
      DefaultRestrictedCountryUpdatedEvent.OutputTuple,
      DefaultRestrictedCountryUpdatedEvent.OutputObject
    >;
    DefaultRestrictedCountryUpdated: TypedContractEvent<
      DefaultRestrictedCountryUpdatedEvent.InputTuple,
      DefaultRestrictedCountryUpdatedEvent.OutputTuple,
      DefaultRestrictedCountryUpdatedEvent.OutputObject
    >;

    "FeeCollectorUpdated(address)": TypedContractEvent<
      FeeCollectorUpdatedEvent.InputTuple,
      FeeCollectorUpdatedEvent.OutputTuple,
      FeeCollectorUpdatedEvent.OutputObject
    >;
    FeeCollectorUpdated: TypedContractEvent<
      FeeCollectorUpdatedEvent.InputTuple,
      FeeCollectorUpdatedEvent.OutputTuple,
      FeeCollectorUpdatedEvent.OutputObject
    >;

    "FeesUpdated(uint256,uint256)": TypedContractEvent<
      FeesUpdatedEvent.InputTuple,
      FeesUpdatedEvent.OutputTuple,
      FeesUpdatedEvent.OutputObject
    >;
    FeesUpdated: TypedContractEvent<
      FeesUpdatedEvent.InputTuple,
      FeesUpdatedEvent.OutputTuple,
      FeesUpdatedEvent.OutputObject
    >;

    "Initialized(uint8)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "KYCVerifierUpdated(address,address)": TypedContractEvent<
      KYCVerifierUpdatedEvent.InputTuple,
      KYCVerifierUpdatedEvent.OutputTuple,
      KYCVerifierUpdatedEvent.OutputObject
    >;
    KYCVerifierUpdated: TypedContractEvent<
      KYCVerifierUpdatedEvent.InputTuple,
      KYCVerifierUpdatedEvent.OutputTuple,
      KYCVerifierUpdatedEvent.OutputObject
    >;

    "OrderCancelled(uint256)": TypedContractEvent<
      OrderCancelledEvent.InputTuple,
      OrderCancelledEvent.OutputTuple,
      OrderCancelledEvent.OutputObject
    >;
    OrderCancelled: TypedContractEvent<
      OrderCancelledEvent.InputTuple,
      OrderCancelledEvent.OutputTuple,
      OrderCancelledEvent.OutputObject
    >;

    "OrderCreated(uint256,address,address,address,uint8,uint256,uint256)": TypedContractEvent<
      OrderCreatedEvent.InputTuple,
      OrderCreatedEvent.OutputTuple,
      OrderCreatedEvent.OutputObject
    >;
    OrderCreated: TypedContractEvent<
      OrderCreatedEvent.InputTuple,
      OrderCreatedEvent.OutputTuple,
      OrderCreatedEvent.OutputObject
    >;

    "OrderFilled(uint256,uint256,uint256)": TypedContractEvent<
      OrderFilledEvent.InputTuple,
      OrderFilledEvent.OutputTuple,
      OrderFilledEvent.OutputObject
    >;
    OrderFilled: TypedContractEvent<
      OrderFilledEvent.InputTuple,
      OrderFilledEvent.OutputTuple,
      OrderFilledEvent.OutputObject
    >;

    "PairCountryRestrictionUpdated(bytes32,uint16,bool)": TypedContractEvent<
      PairCountryRestrictionUpdatedEvent.InputTuple,
      PairCountryRestrictionUpdatedEvent.OutputTuple,
      PairCountryRestrictionUpdatedEvent.OutputObject
    >;
    PairCountryRestrictionUpdated: TypedContractEvent<
      PairCountryRestrictionUpdatedEvent.InputTuple,
      PairCountryRestrictionUpdatedEvent.OutputTuple,
      PairCountryRestrictionUpdatedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "TradeExecuted(uint256,uint256,uint256,address,address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      TradeExecutedEvent.InputTuple,
      TradeExecutedEvent.OutputTuple,
      TradeExecutedEvent.OutputObject
    >;
    TradeExecuted: TypedContractEvent<
      TradeExecutedEvent.InputTuple,
      TradeExecutedEvent.OutputTuple,
      TradeExecutedEvent.OutputObject
    >;

    "TradingPairCreated(address,address,bytes32,uint8)": TypedContractEvent<
      TradingPairCreatedEvent.InputTuple,
      TradingPairCreatedEvent.OutputTuple,
      TradingPairCreatedEvent.OutputObject
    >;
    TradingPairCreated: TypedContractEvent<
      TradingPairCreatedEvent.InputTuple,
      TradingPairCreatedEvent.OutputTuple,
      TradingPairCreatedEvent.OutputObject
    >;

    "TradingPairKYCLevelChanged(bytes32,uint8,uint8)": TypedContractEvent<
      TradingPairKYCLevelChangedEvent.InputTuple,
      TradingPairKYCLevelChangedEvent.OutputTuple,
      TradingPairKYCLevelChangedEvent.OutputObject
    >;
    TradingPairKYCLevelChanged: TypedContractEvent<
      TradingPairKYCLevelChangedEvent.InputTuple,
      TradingPairKYCLevelChangedEvent.OutputTuple,
      TradingPairKYCLevelChangedEvent.OutputObject
    >;

    "TradingPairStatusChanged(bytes32,bool)": TypedContractEvent<
      TradingPairStatusChangedEvent.InputTuple,
      TradingPairStatusChangedEvent.OutputTuple,
      TradingPairStatusChangedEvent.OutputObject
    >;
    TradingPairStatusChanged: TypedContractEvent<
      TradingPairStatusChangedEvent.InputTuple,
      TradingPairStatusChangedEvent.OutputTuple,
      TradingPairStatusChangedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
