/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace RWASecurityToken {
  export type KYCProofStruct = {
    level: BigNumberish;
    countryCode: BigNumberish;
    expiry: BigNumberish;
    signature: BytesLike;
  };

  export type KYCProofStructOutput = [
    level: bigint,
    countryCode: bigint,
    expiry: bigint,
    signature: string
  ] & { level: bigint; countryCode: bigint; expiry: bigint; signature: string };
}

export interface RWASecurityTokenInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "AGENT_ROLE"
      | "BURNER_ROLE"
      | "COMPLIANCE_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "MINTER_ROLE"
      | "RECOVERY_ROLE"
      | "SNAPSHOT_ROLE"
      | "allowance"
      | "approve"
      | "balanceOf"
      | "balanceOfAt"
      | "batchBurn"
      | "batchCacheKYC"
      | "batchForcedTransfer"
      | "batchFreezePartialTokens"
      | "batchMint"
      | "batchSetAddressFrozen"
      | "batchUnfreezePartialTokens"
      | "burn"
      | "cacheKYC"
      | "compliance"
      | "decimals"
      | "decreaseAllowance"
      | "forcedTransfer"
      | "freezePartialTokens"
      | "getCachedKYC"
      | "getCurrentSnapshotId"
      | "getFrozenTokens"
      | "getKYCVerifier"
      | "getRoleAdmin"
      | "getSnapshotBlock"
      | "getUnfrozenBalance"
      | "grantRole"
      | "hasRole"
      | "increaseAllowance"
      | "initialize"
      | "isCountryRestricted"
      | "isFrozen"
      | "isKYCValid"
      | "isPaymentProcessed"
      | "kycCacheValidityDuration"
      | "kycEnforced"
      | "kycVerifier"
      | "maxSupply"
      | "minKYCLevel"
      | "mint"
      | "mintForOffChainPayment"
      | "mintWithKYC"
      | "name"
      | "onchainID"
      | "pause"
      | "paused"
      | "proxiableUUID"
      | "recoveryAddress"
      | "renounceRole"
      | "revokeRole"
      | "setAddressFrozen"
      | "setCompliance"
      | "setCountryRestriction"
      | "setKYCCacheValidityDuration"
      | "setKYCEnforced"
      | "setKYCVerifier"
      | "setMaxSupply"
      | "setMinKYCLevel"
      | "setName"
      | "setOnchainID"
      | "setSymbol"
      | "snapshot"
      | "supportsInterface"
      | "symbol"
      | "totalSupply"
      | "totalSupplyAt"
      | "transfer"
      | "transferFrom"
      | "unfreezePartialTokens"
      | "unpause"
      | "upgradeTo"
      | "upgradeToAndCall"
      | "version"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AddressFrozen"
      | "AdminChanged"
      | "Approval"
      | "BeaconUpgraded"
      | "ComplianceAdded"
      | "CountryRestrictionUpdated"
      | "Initialized"
      | "KYCCached"
      | "KYCEnforcementUpdated"
      | "KYCVerifierUpdated"
      | "MaxSupplyUpdated"
      | "MinKYCLevelUpdated"
      | "OffChainPaymentMinted"
      | "Paused"
      | "RecoverySuccess"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "Snapshot"
      | "SnapshotCreated"
      | "TokensBurned"
      | "TokensFrozen"
      | "TokensMinted"
      | "TokensUnfrozen"
      | "Transfer"
      | "Unpaused"
      | "UpdatedTokenInformation"
      | "Upgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "AGENT_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BURNER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "COMPLIANCE_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MINTER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RECOVERY_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SNAPSHOT_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allowance",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOfAt",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "batchBurn",
    values: [AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "batchCacheKYC",
    values: [AddressLike[], RWASecurityToken.KYCProofStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "batchForcedTransfer",
    values: [AddressLike[], AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "batchFreezePartialTokens",
    values: [AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "batchMint",
    values: [AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "batchSetAddressFrozen",
    values: [AddressLike[], boolean[]]
  ): string;
  encodeFunctionData(
    functionFragment: "batchUnfreezePartialTokens",
    values: [AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "burn",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cacheKYC",
    values: [AddressLike, RWASecurityToken.KYCProofStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "compliance",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "decreaseAllowance",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "forcedTransfer",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "freezePartialTokens",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCachedKYC",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentSnapshotId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFrozenTokens",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getKYCVerifier",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSnapshotBlock",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUnfrozenBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "increaseAllowance",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      string,
      string,
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "isCountryRestricted",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isFrozen",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isKYCValid",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isPaymentProcessed",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "kycCacheValidityDuration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "kycEnforced",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "kycVerifier",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "maxSupply", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "minKYCLevel",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mint",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintForOffChainPayment",
    values: [AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "mintWithKYC",
    values: [AddressLike, BigNumberish, RWASecurityToken.KYCProofStruct]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "onchainID", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recoveryAddress",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAddressFrozen",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setCompliance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setCountryRestriction",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setKYCCacheValidityDuration",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setKYCEnforced",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setKYCVerifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxSupply",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinKYCLevel",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "setName", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setOnchainID",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "setSymbol", values: [string]): string;
  encodeFunctionData(functionFragment: "snapshot", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupplyAt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unfreezePartialTokens",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "upgradeTo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;

  decodeFunctionResult(functionFragment: "AGENT_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "BURNER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "COMPLIANCE_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MINTER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RECOVERY_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SNAPSHOT_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allowance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "balanceOfAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "batchBurn", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "batchCacheKYC",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchForcedTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchFreezePartialTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "batchMint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "batchSetAddressFrozen",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchUnfreezePartialTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "burn", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cacheKYC", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "compliance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "decreaseAllowance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "forcedTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "freezePartialTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCachedKYC",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentSnapshotId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFrozenTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getKYCVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSnapshotBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUnfrozenBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "increaseAllowance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isCountryRestricted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isFrozen", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isKYCValid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isPaymentProcessed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "kycCacheValidityDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "kycEnforced",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "kycVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "maxSupply", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "minKYCLevel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "mintForOffChainPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintWithKYC",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "onchainID", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recoveryAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAddressFrozen",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCompliance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCountryRestriction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setKYCCacheValidityDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setKYCEnforced",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setKYCVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinKYCLevel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setName", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setOnchainID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setSymbol", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "snapshot", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSupplyAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unfreezePartialTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "upgradeTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;
}

export namespace AddressFrozenEvent {
  export type InputTuple = [
    _userAddress: AddressLike,
    _isFrozen: boolean,
    _owner: AddressLike
  ];
  export type OutputTuple = [
    _userAddress: string,
    _isFrozen: boolean,
    _owner: string
  ];
  export interface OutputObject {
    _userAddress: string;
    _isFrozen: boolean;
    _owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AdminChangedEvent {
  export type InputTuple = [previousAdmin: AddressLike, newAdmin: AddressLike];
  export type OutputTuple = [previousAdmin: string, newAdmin: string];
  export interface OutputObject {
    previousAdmin: string;
    newAdmin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    spender: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [owner: string, spender: string, value: bigint];
  export interface OutputObject {
    owner: string;
    spender: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BeaconUpgradedEvent {
  export type InputTuple = [beacon: AddressLike];
  export type OutputTuple = [beacon: string];
  export interface OutputObject {
    beacon: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ComplianceAddedEvent {
  export type InputTuple = [_compliance: AddressLike];
  export type OutputTuple = [_compliance: string];
  export interface OutputObject {
    _compliance: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CountryRestrictionUpdatedEvent {
  export type InputTuple = [countryCode: BigNumberish, restricted: boolean];
  export type OutputTuple = [countryCode: bigint, restricted: boolean];
  export interface OutputObject {
    countryCode: bigint;
    restricted: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace KYCCachedEvent {
  export type InputTuple = [
    wallet: AddressLike,
    level: BigNumberish,
    countryCode: BigNumberish,
    expiry: BigNumberish
  ];
  export type OutputTuple = [
    wallet: string,
    level: bigint,
    countryCode: bigint,
    expiry: bigint
  ];
  export interface OutputObject {
    wallet: string;
    level: bigint;
    countryCode: bigint;
    expiry: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace KYCEnforcementUpdatedEvent {
  export type InputTuple = [enforced: boolean];
  export type OutputTuple = [enforced: boolean];
  export interface OutputObject {
    enforced: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace KYCVerifierUpdatedEvent {
  export type InputTuple = [oldVerifier: AddressLike, newVerifier: AddressLike];
  export type OutputTuple = [oldVerifier: string, newVerifier: string];
  export interface OutputObject {
    oldVerifier: string;
    newVerifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MaxSupplyUpdatedEvent {
  export type InputTuple = [
    oldMaxSupply: BigNumberish,
    newMaxSupply: BigNumberish
  ];
  export type OutputTuple = [oldMaxSupply: bigint, newMaxSupply: bigint];
  export interface OutputObject {
    oldMaxSupply: bigint;
    newMaxSupply: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MinKYCLevelUpdatedEvent {
  export type InputTuple = [oldLevel: BigNumberish, newLevel: BigNumberish];
  export type OutputTuple = [oldLevel: bigint, newLevel: bigint];
  export interface OutputObject {
    oldLevel: bigint;
    newLevel: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OffChainPaymentMintedEvent {
  export type InputTuple = [
    to: AddressLike,
    amount: BigNumberish,
    paymentReference: string
  ];
  export type OutputTuple = [
    to: string,
    amount: bigint,
    paymentReference: string
  ];
  export interface OutputObject {
    to: string;
    amount: bigint;
    paymentReference: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecoverySuccessEvent {
  export type InputTuple = [
    _lostWallet: AddressLike,
    _newWallet: AddressLike,
    _investorOnchainID: AddressLike
  ];
  export type OutputTuple = [
    _lostWallet: string,
    _newWallet: string,
    _investorOnchainID: string
  ];
  export interface OutputObject {
    _lostWallet: string;
    _newWallet: string;
    _investorOnchainID: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SnapshotEvent {
  export type InputTuple = [id: BigNumberish];
  export type OutputTuple = [id: bigint];
  export interface OutputObject {
    id: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SnapshotCreatedEvent {
  export type InputTuple = [
    snapshotId: BigNumberish,
    blockNumber: BigNumberish
  ];
  export type OutputTuple = [snapshotId: bigint, blockNumber: bigint];
  export interface OutputObject {
    snapshotId: bigint;
    blockNumber: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensBurnedEvent {
  export type InputTuple = [from: AddressLike, amount: BigNumberish];
  export type OutputTuple = [from: string, amount: bigint];
  export interface OutputObject {
    from: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensFrozenEvent {
  export type InputTuple = [_userAddress: AddressLike, _amount: BigNumberish];
  export type OutputTuple = [_userAddress: string, _amount: bigint];
  export interface OutputObject {
    _userAddress: string;
    _amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensMintedEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensUnfrozenEvent {
  export type InputTuple = [_userAddress: AddressLike, _amount: BigNumberish];
  export type OutputTuple = [_userAddress: string, _amount: bigint];
  export interface OutputObject {
    _userAddress: string;
    _amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, value: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdatedTokenInformationEvent {
  export type InputTuple = [
    _newName: string,
    _newSymbol: string,
    _newDecimals: BigNumberish,
    _newVersion: string,
    _newOnchainID: AddressLike
  ];
  export type OutputTuple = [
    _newName: string,
    _newSymbol: string,
    _newDecimals: bigint,
    _newVersion: string,
    _newOnchainID: string
  ];
  export interface OutputObject {
    _newName: string;
    _newSymbol: string;
    _newDecimals: bigint;
    _newVersion: string;
    _newOnchainID: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RWASecurityToken extends BaseContract {
  connect(runner?: ContractRunner | null): RWASecurityToken;
  waitForDeployment(): Promise<this>;

  interface: RWASecurityTokenInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  AGENT_ROLE: TypedContractMethod<[], [string], "view">;

  BURNER_ROLE: TypedContractMethod<[], [string], "view">;

  COMPLIANCE_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  MINTER_ROLE: TypedContractMethod<[], [string], "view">;

  RECOVERY_ROLE: TypedContractMethod<[], [string], "view">;

  SNAPSHOT_ROLE: TypedContractMethod<[], [string], "view">;

  allowance: TypedContractMethod<
    [owner: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;

  approve: TypedContractMethod<
    [spender: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  balanceOf: TypedContractMethod<[account: AddressLike], [bigint], "view">;

  balanceOfAt: TypedContractMethod<
    [account: AddressLike, snapshotId: BigNumberish],
    [bigint],
    "view"
  >;

  batchBurn: TypedContractMethod<
    [_addrs: AddressLike[], _amounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  batchCacheKYC: TypedContractMethod<
    [_wallets: AddressLike[], _proofs: RWASecurityToken.KYCProofStruct[]],
    [void],
    "nonpayable"
  >;

  batchForcedTransfer: TypedContractMethod<
    [
      _fromList: AddressLike[],
      _toList: AddressLike[],
      _amounts: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  batchFreezePartialTokens: TypedContractMethod<
    [_addrs: AddressLike[], _amounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  batchMint: TypedContractMethod<
    [_toList: AddressLike[], _amounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  batchSetAddressFrozen: TypedContractMethod<
    [_addrs: AddressLike[], _freeze: boolean[]],
    [void],
    "nonpayable"
  >;

  batchUnfreezePartialTokens: TypedContractMethod<
    [_addrs: AddressLike[], _amounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  burn: TypedContractMethod<
    [_userAddress: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  cacheKYC: TypedContractMethod<
    [_wallet: AddressLike, _proof: RWASecurityToken.KYCProofStruct],
    [void],
    "nonpayable"
  >;

  compliance: TypedContractMethod<[], [string], "view">;

  decimals: TypedContractMethod<[], [bigint], "view">;

  decreaseAllowance: TypedContractMethod<
    [spender: AddressLike, subtractedValue: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  forcedTransfer: TypedContractMethod<
    [_from: AddressLike, _to: AddressLike, _amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  freezePartialTokens: TypedContractMethod<
    [_userAddress: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getCachedKYC: TypedContractMethod<
    [_wallet: AddressLike],
    [[bigint, bigint, bigint, bigint, boolean]],
    "view"
  >;

  getCurrentSnapshotId: TypedContractMethod<[], [bigint], "view">;

  getFrozenTokens: TypedContractMethod<[_addr: AddressLike], [bigint], "view">;

  getKYCVerifier: TypedContractMethod<[], [string], "view">;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getSnapshotBlock: TypedContractMethod<[_id: BigNumberish], [bigint], "view">;

  getUnfrozenBalance: TypedContractMethod<
    [_addr: AddressLike],
    [bigint],
    "view"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  increaseAllowance: TypedContractMethod<
    [spender: AddressLike, addedValue: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  initialize: TypedContractMethod<
    [
      _name: string,
      _symbol: string,
      _admin: AddressLike,
      _compliance: AddressLike,
      _kycVerifier: AddressLike,
      _maxSupply: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  isCountryRestricted: TypedContractMethod<
    [_code: BigNumberish],
    [boolean],
    "view"
  >;

  isFrozen: TypedContractMethod<[_addr: AddressLike], [boolean], "view">;

  isKYCValid: TypedContractMethod<[_wallet: AddressLike], [boolean], "view">;

  isPaymentProcessed: TypedContractMethod<[_ref: string], [boolean], "view">;

  kycCacheValidityDuration: TypedContractMethod<[], [bigint], "view">;

  kycEnforced: TypedContractMethod<[], [boolean], "view">;

  kycVerifier: TypedContractMethod<[], [string], "view">;

  maxSupply: TypedContractMethod<[], [bigint], "view">;

  minKYCLevel: TypedContractMethod<[], [bigint], "view">;

  mint: TypedContractMethod<
    [_to: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  mintForOffChainPayment: TypedContractMethod<
    [_to: AddressLike, _amount: BigNumberish, _ref: string],
    [void],
    "nonpayable"
  >;

  mintWithKYC: TypedContractMethod<
    [
      _to: AddressLike,
      _amount: BigNumberish,
      _proof: RWASecurityToken.KYCProofStruct
    ],
    [void],
    "nonpayable"
  >;

  name: TypedContractMethod<[], [string], "view">;

  onchainID: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  recoveryAddress: TypedContractMethod<
    [
      _lostWallet: AddressLike,
      _newWallet: AddressLike,
      _investorOnchainID: AddressLike
    ],
    [boolean],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setAddressFrozen: TypedContractMethod<
    [_userAddress: AddressLike, _freeze: boolean],
    [void],
    "nonpayable"
  >;

  setCompliance: TypedContractMethod<
    [_compliance: AddressLike],
    [void],
    "nonpayable"
  >;

  setCountryRestriction: TypedContractMethod<
    [_countryCode: BigNumberish, _restricted: boolean],
    [void],
    "nonpayable"
  >;

  setKYCCacheValidityDuration: TypedContractMethod<
    [_duration: BigNumberish],
    [void],
    "nonpayable"
  >;

  setKYCEnforced: TypedContractMethod<
    [_enforced: boolean],
    [void],
    "nonpayable"
  >;

  setKYCVerifier: TypedContractMethod<
    [_kycVerifier: AddressLike],
    [void],
    "nonpayable"
  >;

  setMaxSupply: TypedContractMethod<
    [_maxSupply: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMinKYCLevel: TypedContractMethod<
    [_level: BigNumberish],
    [void],
    "nonpayable"
  >;

  setName: TypedContractMethod<[_name: string], [void], "nonpayable">;

  setOnchainID: TypedContractMethod<
    [_onchainID: AddressLike],
    [void],
    "nonpayable"
  >;

  setSymbol: TypedContractMethod<[_symbol: string], [void], "nonpayable">;

  snapshot: TypedContractMethod<[], [bigint], "nonpayable">;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  symbol: TypedContractMethod<[], [string], "view">;

  totalSupply: TypedContractMethod<[], [bigint], "view">;

  totalSupplyAt: TypedContractMethod<
    [snapshotId: BigNumberish],
    [bigint],
    "view"
  >;

  transfer: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  transferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  unfreezePartialTokens: TypedContractMethod<
    [_userAddress: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  upgradeTo: TypedContractMethod<
    [newImplementation: AddressLike],
    [void],
    "nonpayable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  version: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "AGENT_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "BURNER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "COMPLIANCE_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MINTER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "RECOVERY_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "SNAPSHOT_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "allowance"
  ): TypedContractMethod<
    [owner: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [spender: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "balanceOfAt"
  ): TypedContractMethod<
    [account: AddressLike, snapshotId: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "batchBurn"
  ): TypedContractMethod<
    [_addrs: AddressLike[], _amounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "batchCacheKYC"
  ): TypedContractMethod<
    [_wallets: AddressLike[], _proofs: RWASecurityToken.KYCProofStruct[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "batchForcedTransfer"
  ): TypedContractMethod<
    [
      _fromList: AddressLike[],
      _toList: AddressLike[],
      _amounts: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "batchFreezePartialTokens"
  ): TypedContractMethod<
    [_addrs: AddressLike[], _amounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "batchMint"
  ): TypedContractMethod<
    [_toList: AddressLike[], _amounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "batchSetAddressFrozen"
  ): TypedContractMethod<
    [_addrs: AddressLike[], _freeze: boolean[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "batchUnfreezePartialTokens"
  ): TypedContractMethod<
    [_addrs: AddressLike[], _amounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "burn"
  ): TypedContractMethod<
    [_userAddress: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cacheKYC"
  ): TypedContractMethod<
    [_wallet: AddressLike, _proof: RWASecurityToken.KYCProofStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "compliance"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "decimals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "decreaseAllowance"
  ): TypedContractMethod<
    [spender: AddressLike, subtractedValue: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "forcedTransfer"
  ): TypedContractMethod<
    [_from: AddressLike, _to: AddressLike, _amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "freezePartialTokens"
  ): TypedContractMethod<
    [_userAddress: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getCachedKYC"
  ): TypedContractMethod<
    [_wallet: AddressLike],
    [[bigint, bigint, bigint, bigint, boolean]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCurrentSnapshotId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getFrozenTokens"
  ): TypedContractMethod<[_addr: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getKYCVerifier"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getSnapshotBlock"
  ): TypedContractMethod<[_id: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUnfrozenBalance"
  ): TypedContractMethod<[_addr: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "increaseAllowance"
  ): TypedContractMethod<
    [spender: AddressLike, addedValue: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      _name: string,
      _symbol: string,
      _admin: AddressLike,
      _compliance: AddressLike,
      _kycVerifier: AddressLike,
      _maxSupply: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isCountryRestricted"
  ): TypedContractMethod<[_code: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "isFrozen"
  ): TypedContractMethod<[_addr: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isKYCValid"
  ): TypedContractMethod<[_wallet: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isPaymentProcessed"
  ): TypedContractMethod<[_ref: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "kycCacheValidityDuration"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "kycEnforced"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "kycVerifier"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "maxSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minKYCLevel"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "mint"
  ): TypedContractMethod<
    [_to: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mintForOffChainPayment"
  ): TypedContractMethod<
    [_to: AddressLike, _amount: BigNumberish, _ref: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mintWithKYC"
  ): TypedContractMethod<
    [
      _to: AddressLike,
      _amount: BigNumberish,
      _proof: RWASecurityToken.KYCProofStruct
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "onchainID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recoveryAddress"
  ): TypedContractMethod<
    [
      _lostWallet: AddressLike,
      _newWallet: AddressLike,
      _investorOnchainID: AddressLike
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAddressFrozen"
  ): TypedContractMethod<
    [_userAddress: AddressLike, _freeze: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setCompliance"
  ): TypedContractMethod<[_compliance: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setCountryRestriction"
  ): TypedContractMethod<
    [_countryCode: BigNumberish, _restricted: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setKYCCacheValidityDuration"
  ): TypedContractMethod<[_duration: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setKYCEnforced"
  ): TypedContractMethod<[_enforced: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setKYCVerifier"
  ): TypedContractMethod<[_kycVerifier: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMaxSupply"
  ): TypedContractMethod<[_maxSupply: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMinKYCLevel"
  ): TypedContractMethod<[_level: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setName"
  ): TypedContractMethod<[_name: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setOnchainID"
  ): TypedContractMethod<[_onchainID: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSymbol"
  ): TypedContractMethod<[_symbol: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "snapshot"
  ): TypedContractMethod<[], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalSupplyAt"
  ): TypedContractMethod<[snapshotId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "transfer"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unfreezePartialTokens"
  ): TypedContractMethod<
    [_userAddress: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeTo"
  ): TypedContractMethod<
    [newImplementation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "version"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "AddressFrozen"
  ): TypedContractEvent<
    AddressFrozenEvent.InputTuple,
    AddressFrozenEvent.OutputTuple,
    AddressFrozenEvent.OutputObject
  >;
  getEvent(
    key: "AdminChanged"
  ): TypedContractEvent<
    AdminChangedEvent.InputTuple,
    AdminChangedEvent.OutputTuple,
    AdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "BeaconUpgraded"
  ): TypedContractEvent<
    BeaconUpgradedEvent.InputTuple,
    BeaconUpgradedEvent.OutputTuple,
    BeaconUpgradedEvent.OutputObject
  >;
  getEvent(
    key: "ComplianceAdded"
  ): TypedContractEvent<
    ComplianceAddedEvent.InputTuple,
    ComplianceAddedEvent.OutputTuple,
    ComplianceAddedEvent.OutputObject
  >;
  getEvent(
    key: "CountryRestrictionUpdated"
  ): TypedContractEvent<
    CountryRestrictionUpdatedEvent.InputTuple,
    CountryRestrictionUpdatedEvent.OutputTuple,
    CountryRestrictionUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "KYCCached"
  ): TypedContractEvent<
    KYCCachedEvent.InputTuple,
    KYCCachedEvent.OutputTuple,
    KYCCachedEvent.OutputObject
  >;
  getEvent(
    key: "KYCEnforcementUpdated"
  ): TypedContractEvent<
    KYCEnforcementUpdatedEvent.InputTuple,
    KYCEnforcementUpdatedEvent.OutputTuple,
    KYCEnforcementUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "KYCVerifierUpdated"
  ): TypedContractEvent<
    KYCVerifierUpdatedEvent.InputTuple,
    KYCVerifierUpdatedEvent.OutputTuple,
    KYCVerifierUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MaxSupplyUpdated"
  ): TypedContractEvent<
    MaxSupplyUpdatedEvent.InputTuple,
    MaxSupplyUpdatedEvent.OutputTuple,
    MaxSupplyUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MinKYCLevelUpdated"
  ): TypedContractEvent<
    MinKYCLevelUpdatedEvent.InputTuple,
    MinKYCLevelUpdatedEvent.OutputTuple,
    MinKYCLevelUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OffChainPaymentMinted"
  ): TypedContractEvent<
    OffChainPaymentMintedEvent.InputTuple,
    OffChainPaymentMintedEvent.OutputTuple,
    OffChainPaymentMintedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RecoverySuccess"
  ): TypedContractEvent<
    RecoverySuccessEvent.InputTuple,
    RecoverySuccessEvent.OutputTuple,
    RecoverySuccessEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "Snapshot"
  ): TypedContractEvent<
    SnapshotEvent.InputTuple,
    SnapshotEvent.OutputTuple,
    SnapshotEvent.OutputObject
  >;
  getEvent(
    key: "SnapshotCreated"
  ): TypedContractEvent<
    SnapshotCreatedEvent.InputTuple,
    SnapshotCreatedEvent.OutputTuple,
    SnapshotCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TokensBurned"
  ): TypedContractEvent<
    TokensBurnedEvent.InputTuple,
    TokensBurnedEvent.OutputTuple,
    TokensBurnedEvent.OutputObject
  >;
  getEvent(
    key: "TokensFrozen"
  ): TypedContractEvent<
    TokensFrozenEvent.InputTuple,
    TokensFrozenEvent.OutputTuple,
    TokensFrozenEvent.OutputObject
  >;
  getEvent(
    key: "TokensMinted"
  ): TypedContractEvent<
    TokensMintedEvent.InputTuple,
    TokensMintedEvent.OutputTuple,
    TokensMintedEvent.OutputObject
  >;
  getEvent(
    key: "TokensUnfrozen"
  ): TypedContractEvent<
    TokensUnfrozenEvent.InputTuple,
    TokensUnfrozenEvent.OutputTuple,
    TokensUnfrozenEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "UpdatedTokenInformation"
  ): TypedContractEvent<
    UpdatedTokenInformationEvent.InputTuple,
    UpdatedTokenInformationEvent.OutputTuple,
    UpdatedTokenInformationEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "AddressFrozen(address,bool,address)": TypedContractEvent<
      AddressFrozenEvent.InputTuple,
      AddressFrozenEvent.OutputTuple,
      AddressFrozenEvent.OutputObject
    >;
    AddressFrozen: TypedContractEvent<
      AddressFrozenEvent.InputTuple,
      AddressFrozenEvent.OutputTuple,
      AddressFrozenEvent.OutputObject
    >;

    "AdminChanged(address,address)": TypedContractEvent<
      AdminChangedEvent.InputTuple,
      AdminChangedEvent.OutputTuple,
      AdminChangedEvent.OutputObject
    >;
    AdminChanged: TypedContractEvent<
      AdminChangedEvent.InputTuple,
      AdminChangedEvent.OutputTuple,
      AdminChangedEvent.OutputObject
    >;

    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "BeaconUpgraded(address)": TypedContractEvent<
      BeaconUpgradedEvent.InputTuple,
      BeaconUpgradedEvent.OutputTuple,
      BeaconUpgradedEvent.OutputObject
    >;
    BeaconUpgraded: TypedContractEvent<
      BeaconUpgradedEvent.InputTuple,
      BeaconUpgradedEvent.OutputTuple,
      BeaconUpgradedEvent.OutputObject
    >;

    "ComplianceAdded(address)": TypedContractEvent<
      ComplianceAddedEvent.InputTuple,
      ComplianceAddedEvent.OutputTuple,
      ComplianceAddedEvent.OutputObject
    >;
    ComplianceAdded: TypedContractEvent<
      ComplianceAddedEvent.InputTuple,
      ComplianceAddedEvent.OutputTuple,
      ComplianceAddedEvent.OutputObject
    >;

    "CountryRestrictionUpdated(uint16,bool)": TypedContractEvent<
      CountryRestrictionUpdatedEvent.InputTuple,
      CountryRestrictionUpdatedEvent.OutputTuple,
      CountryRestrictionUpdatedEvent.OutputObject
    >;
    CountryRestrictionUpdated: TypedContractEvent<
      CountryRestrictionUpdatedEvent.InputTuple,
      CountryRestrictionUpdatedEvent.OutputTuple,
      CountryRestrictionUpdatedEvent.OutputObject
    >;

    "Initialized(uint8)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "KYCCached(address,uint8,uint16,uint256)": TypedContractEvent<
      KYCCachedEvent.InputTuple,
      KYCCachedEvent.OutputTuple,
      KYCCachedEvent.OutputObject
    >;
    KYCCached: TypedContractEvent<
      KYCCachedEvent.InputTuple,
      KYCCachedEvent.OutputTuple,
      KYCCachedEvent.OutputObject
    >;

    "KYCEnforcementUpdated(bool)": TypedContractEvent<
      KYCEnforcementUpdatedEvent.InputTuple,
      KYCEnforcementUpdatedEvent.OutputTuple,
      KYCEnforcementUpdatedEvent.OutputObject
    >;
    KYCEnforcementUpdated: TypedContractEvent<
      KYCEnforcementUpdatedEvent.InputTuple,
      KYCEnforcementUpdatedEvent.OutputTuple,
      KYCEnforcementUpdatedEvent.OutputObject
    >;

    "KYCVerifierUpdated(address,address)": TypedContractEvent<
      KYCVerifierUpdatedEvent.InputTuple,
      KYCVerifierUpdatedEvent.OutputTuple,
      KYCVerifierUpdatedEvent.OutputObject
    >;
    KYCVerifierUpdated: TypedContractEvent<
      KYCVerifierUpdatedEvent.InputTuple,
      KYCVerifierUpdatedEvent.OutputTuple,
      KYCVerifierUpdatedEvent.OutputObject
    >;

    "MaxSupplyUpdated(uint256,uint256)": TypedContractEvent<
      MaxSupplyUpdatedEvent.InputTuple,
      MaxSupplyUpdatedEvent.OutputTuple,
      MaxSupplyUpdatedEvent.OutputObject
    >;
    MaxSupplyUpdated: TypedContractEvent<
      MaxSupplyUpdatedEvent.InputTuple,
      MaxSupplyUpdatedEvent.OutputTuple,
      MaxSupplyUpdatedEvent.OutputObject
    >;

    "MinKYCLevelUpdated(uint8,uint8)": TypedContractEvent<
      MinKYCLevelUpdatedEvent.InputTuple,
      MinKYCLevelUpdatedEvent.OutputTuple,
      MinKYCLevelUpdatedEvent.OutputObject
    >;
    MinKYCLevelUpdated: TypedContractEvent<
      MinKYCLevelUpdatedEvent.InputTuple,
      MinKYCLevelUpdatedEvent.OutputTuple,
      MinKYCLevelUpdatedEvent.OutputObject
    >;

    "OffChainPaymentMinted(address,uint256,string)": TypedContractEvent<
      OffChainPaymentMintedEvent.InputTuple,
      OffChainPaymentMintedEvent.OutputTuple,
      OffChainPaymentMintedEvent.OutputObject
    >;
    OffChainPaymentMinted: TypedContractEvent<
      OffChainPaymentMintedEvent.InputTuple,
      OffChainPaymentMintedEvent.OutputTuple,
      OffChainPaymentMintedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RecoverySuccess(address,address,address)": TypedContractEvent<
      RecoverySuccessEvent.InputTuple,
      RecoverySuccessEvent.OutputTuple,
      RecoverySuccessEvent.OutputObject
    >;
    RecoverySuccess: TypedContractEvent<
      RecoverySuccessEvent.InputTuple,
      RecoverySuccessEvent.OutputTuple,
      RecoverySuccessEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "Snapshot(uint256)": TypedContractEvent<
      SnapshotEvent.InputTuple,
      SnapshotEvent.OutputTuple,
      SnapshotEvent.OutputObject
    >;
    Snapshot: TypedContractEvent<
      SnapshotEvent.InputTuple,
      SnapshotEvent.OutputTuple,
      SnapshotEvent.OutputObject
    >;

    "SnapshotCreated(uint256,uint256)": TypedContractEvent<
      SnapshotCreatedEvent.InputTuple,
      SnapshotCreatedEvent.OutputTuple,
      SnapshotCreatedEvent.OutputObject
    >;
    SnapshotCreated: TypedContractEvent<
      SnapshotCreatedEvent.InputTuple,
      SnapshotCreatedEvent.OutputTuple,
      SnapshotCreatedEvent.OutputObject
    >;

    "TokensBurned(address,uint256)": TypedContractEvent<
      TokensBurnedEvent.InputTuple,
      TokensBurnedEvent.OutputTuple,
      TokensBurnedEvent.OutputObject
    >;
    TokensBurned: TypedContractEvent<
      TokensBurnedEvent.InputTuple,
      TokensBurnedEvent.OutputTuple,
      TokensBurnedEvent.OutputObject
    >;

    "TokensFrozen(address,uint256)": TypedContractEvent<
      TokensFrozenEvent.InputTuple,
      TokensFrozenEvent.OutputTuple,
      TokensFrozenEvent.OutputObject
    >;
    TokensFrozen: TypedContractEvent<
      TokensFrozenEvent.InputTuple,
      TokensFrozenEvent.OutputTuple,
      TokensFrozenEvent.OutputObject
    >;

    "TokensMinted(address,uint256)": TypedContractEvent<
      TokensMintedEvent.InputTuple,
      TokensMintedEvent.OutputTuple,
      TokensMintedEvent.OutputObject
    >;
    TokensMinted: TypedContractEvent<
      TokensMintedEvent.InputTuple,
      TokensMintedEvent.OutputTuple,
      TokensMintedEvent.OutputObject
    >;

    "TokensUnfrozen(address,uint256)": TypedContractEvent<
      TokensUnfrozenEvent.InputTuple,
      TokensUnfrozenEvent.OutputTuple,
      TokensUnfrozenEvent.OutputObject
    >;
    TokensUnfrozen: TypedContractEvent<
      TokensUnfrozenEvent.InputTuple,
      TokensUnfrozenEvent.OutputTuple,
      TokensUnfrozenEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "UpdatedTokenInformation(string,string,uint8,string,address)": TypedContractEvent<
      UpdatedTokenInformationEvent.InputTuple,
      UpdatedTokenInformationEvent.OutputTuple,
      UpdatedTokenInformationEvent.OutputObject
    >;
    UpdatedTokenInformation: TypedContractEvent<
      UpdatedTokenInformationEvent.InputTuple,
      UpdatedTokenInformationEvent.OutputTuple,
      UpdatedTokenInformationEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
