/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRWAAssetNFT,
  IRWAAssetNFTInterface,
} from "../../../../contracts/tokenize/RWATokenizationFactory.sol/IRWAAssetNFT";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_securityToken",
        type: "address",
      },
    ],
    name: "linkSecurityToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_to",
        type: "address",
      },
      {
        internalType: "string",
        name: "_tokenURI",
        type: "string",
      },
    ],
    name: "mint",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "operator",
        type: "address",
      },
      {
        internalType: "bool",
        name: "approved",
        type: "bool",
      },
    ],
    name: "setApprovalForAll",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IRWAAssetNFT__factory {
  static readonly abi = _abi;
  static createInterface(): IRWAAssetNFTInterface {
    return new Interface(_abi) as IRWAAssetNFTInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IRWAAssetNFT {
    return new Contract(address, _abi, runner) as unknown as IRWAAssetNFT;
  }
}
