/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace RWALaunchpadFactory {
  export type DeploymentRecordStruct = {
    projectId: BigNumberish;
    securityToken: AddressLike;
    escrowVault: AddressLike;
    compliance: AddressLike;
    deployer: AddressLike;
    deployedAt: BigNumberish;
    active: boolean;
  };

  export type DeploymentRecordStructOutput = [
    projectId: bigint,
    securityToken: string,
    escrowVault: string,
    compliance: string,
    deployer: string,
    deployedAt: bigint,
    active: boolean
  ] & {
    projectId: bigint;
    securityToken: string;
    escrowVault: string;
    compliance: string;
    deployer: string;
    deployedAt: bigint;
    active: boolean;
  };

  export type ImplementationAddressesStruct = {
    securityToken: AddressLike;
    escrowVault: AddressLike;
    compliance: AddressLike;
    identityRegistry: AddressLike;
    dividendDistributor: AddressLike;
  };

  export type ImplementationAddressesStructOutput = [
    securityToken: string,
    escrowVault: string,
    compliance: string,
    identityRegistry: string,
    dividendDistributor: string
  ] & {
    securityToken: string;
    escrowVault: string;
    compliance: string;
    identityRegistry: string;
    dividendDistributor: string;
  };
}

export interface RWALaunchpadFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approvedDeployers"
      | "batchSetDeployerApproval"
      | "creationFee"
      | "deactivateProject"
      | "defaultPriceFeed"
      | "deployProject"
      | "deployerProjects"
      | "deployments"
      | "getActiveProjects"
      | "getDeployerProjectCount"
      | "getDeployerProjects"
      | "getDeployment"
      | "getImplementations"
      | "implementations"
      | "initialize"
      | "isDeployerApproved"
      | "owner"
      | "pause"
      | "paused"
      | "platformFeeBps"
      | "platformFeeRecipient"
      | "projectCounter"
      | "projectNFT"
      | "proxiableUUID"
      | "renounceOwnership"
      | "requireApproval"
      | "setComplianceImplementation"
      | "setCreationFee"
      | "setDefaultPriceFeed"
      | "setDeployerApproval"
      | "setDividendDistributorImplementation"
      | "setEscrowVaultImplementation"
      | "setIdentityRegistry"
      | "setPlatformFeeBps"
      | "setPlatformFeeRecipient"
      | "setProjectNFT"
      | "setRequireApproval"
      | "setSecurityTokenImplementation"
      | "transferOwnership"
      | "unpause"
      | "upgradeTo"
      | "upgradeToAndCall"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdminChanged"
      | "BeaconUpgraded"
      | "CreationFeeUpdated"
      | "DefaultPriceFeedUpdated"
      | "DeployerApprovalUpdated"
      | "FeeRecipientUpdated"
      | "ImplementationUpdated"
      | "Initialized"
      | "OwnershipTransferred"
      | "Paused"
      | "PlatformFeeUpdated"
      | "ProjectDeactivated"
      | "ProjectDeployed"
      | "ProjectNFTUpdated"
      | "Unpaused"
      | "Upgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approvedDeployers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "batchSetDeployerApproval",
    values: [AddressLike[], boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "creationFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateProject",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "defaultPriceFeed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deployProject",
    values: [
      string,
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      AddressLike,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "deployerProjects",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deployments",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveProjects",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDeployerProjectCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDeployerProjects",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDeployment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getImplementations",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "implementations",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "isDeployerApproved",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "platformFeeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "projectCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "projectNFT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requireApproval",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setComplianceImplementation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setCreationFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDefaultPriceFeed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setDeployerApproval",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setDividendDistributorImplementation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setEscrowVaultImplementation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setIdentityRegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformFeeBps",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformFeeRecipient",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setProjectNFT",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setRequireApproval",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setSecurityTokenImplementation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "upgradeTo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "approvedDeployers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchSetDeployerApproval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creationFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateProject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "defaultPriceFeed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployProject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployerProjects",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveProjects",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDeployerProjectCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDeployerProjects",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDeployment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getImplementations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "implementations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isDeployerApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "platformFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "projectCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "projectNFT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requireApproval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setComplianceImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCreationFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDefaultPriceFeed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDeployerApproval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDividendDistributorImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setEscrowVaultImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setIdentityRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProjectNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRequireApproval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSecurityTokenImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "upgradeTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
}

export namespace AdminChangedEvent {
  export type InputTuple = [previousAdmin: AddressLike, newAdmin: AddressLike];
  export type OutputTuple = [previousAdmin: string, newAdmin: string];
  export interface OutputObject {
    previousAdmin: string;
    newAdmin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BeaconUpgradedEvent {
  export type InputTuple = [beacon: AddressLike];
  export type OutputTuple = [beacon: string];
  export interface OutputObject {
    beacon: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CreationFeeUpdatedEvent {
  export type InputTuple = [oldFee: BigNumberish, newFee: BigNumberish];
  export type OutputTuple = [oldFee: bigint, newFee: bigint];
  export interface OutputObject {
    oldFee: bigint;
    newFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DefaultPriceFeedUpdatedEvent {
  export type InputTuple = [oldFeed: AddressLike, newFeed: AddressLike];
  export type OutputTuple = [oldFeed: string, newFeed: string];
  export interface OutputObject {
    oldFeed: string;
    newFeed: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DeployerApprovalUpdatedEvent {
  export type InputTuple = [deployer: AddressLike, approved: boolean];
  export type OutputTuple = [deployer: string, approved: boolean];
  export interface OutputObject {
    deployer: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeRecipientUpdatedEvent {
  export type InputTuple = [
    oldRecipient: AddressLike,
    newRecipient: AddressLike
  ];
  export type OutputTuple = [oldRecipient: string, newRecipient: string];
  export interface OutputObject {
    oldRecipient: string;
    newRecipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ImplementationUpdatedEvent {
  export type InputTuple = [
    contractType: string,
    oldImpl: AddressLike,
    newImpl: AddressLike
  ];
  export type OutputTuple = [
    contractType: string,
    oldImpl: string,
    newImpl: string
  ];
  export interface OutputObject {
    contractType: string;
    oldImpl: string;
    newImpl: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformFeeUpdatedEvent {
  export type InputTuple = [oldFee: BigNumberish, newFee: BigNumberish];
  export type OutputTuple = [oldFee: bigint, newFee: bigint];
  export interface OutputObject {
    oldFee: bigint;
    newFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProjectDeactivatedEvent {
  export type InputTuple = [projectId: BigNumberish];
  export type OutputTuple = [projectId: bigint];
  export interface OutputObject {
    projectId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProjectDeployedEvent {
  export type InputTuple = [
    projectId: BigNumberish,
    deployer: AddressLike,
    securityToken: AddressLike,
    escrowVault: AddressLike,
    compliance: AddressLike
  ];
  export type OutputTuple = [
    projectId: bigint,
    deployer: string,
    securityToken: string,
    escrowVault: string,
    compliance: string
  ];
  export interface OutputObject {
    projectId: bigint;
    deployer: string;
    securityToken: string;
    escrowVault: string;
    compliance: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProjectNFTUpdatedEvent {
  export type InputTuple = [oldNFT: AddressLike, newNFT: AddressLike];
  export type OutputTuple = [oldNFT: string, newNFT: string];
  export interface OutputObject {
    oldNFT: string;
    newNFT: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RWALaunchpadFactory extends BaseContract {
  connect(runner?: ContractRunner | null): RWALaunchpadFactory;
  waitForDeployment(): Promise<this>;

  interface: RWALaunchpadFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approvedDeployers: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  batchSetDeployerApproval: TypedContractMethod<
    [_deployers: AddressLike[], _approved: boolean],
    [void],
    "nonpayable"
  >;

  creationFee: TypedContractMethod<[], [bigint], "view">;

  deactivateProject: TypedContractMethod<
    [_projectId: BigNumberish],
    [void],
    "nonpayable"
  >;

  defaultPriceFeed: TypedContractMethod<[], [string], "view">;

  deployProject: TypedContractMethod<
    [
      _name: string,
      _symbol: string,
      _category: string,
      _maxSupply: BigNumberish,
      _fundingGoal: BigNumberish,
      _deadlineDays: BigNumberish,
      _paymentToken: AddressLike,
      _metadataUri: string
    ],
    [
      [bigint, string, string, string] & {
        projectId: bigint;
        securityToken: string;
        escrowVault: string;
        compliance: string;
      }
    ],
    "payable"
  >;

  deployerProjects: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  deployments: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, string, bigint, boolean] & {
        projectId: bigint;
        securityToken: string;
        escrowVault: string;
        compliance: string;
        deployer: string;
        deployedAt: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  getActiveProjects: TypedContractMethod<
    [_offset: BigNumberish, _limit: BigNumberish],
    [bigint[]],
    "view"
  >;

  getDeployerProjectCount: TypedContractMethod<
    [_deployer: AddressLike],
    [bigint],
    "view"
  >;

  getDeployerProjects: TypedContractMethod<
    [_deployer: AddressLike],
    [bigint[]],
    "view"
  >;

  getDeployment: TypedContractMethod<
    [_projectId: BigNumberish],
    [RWALaunchpadFactory.DeploymentRecordStructOutput],
    "view"
  >;

  getImplementations: TypedContractMethod<
    [],
    [RWALaunchpadFactory.ImplementationAddressesStructOutput],
    "view"
  >;

  implementations: TypedContractMethod<
    [],
    [
      [string, string, string, string, string] & {
        securityToken: string;
        escrowVault: string;
        compliance: string;
        identityRegistry: string;
        dividendDistributor: string;
      }
    ],
    "view"
  >;

  initialize: TypedContractMethod<
    [
      _admin: AddressLike,
      _securityTokenImpl: AddressLike,
      _escrowVaultImpl: AddressLike,
      _complianceImpl: AddressLike,
      _identityRegistry: AddressLike,
      _projectNFT: AddressLike,
      _feeRecipient: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  isDeployerApproved: TypedContractMethod<
    [_deployer: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  platformFeeBps: TypedContractMethod<[], [bigint], "view">;

  platformFeeRecipient: TypedContractMethod<[], [string], "view">;

  projectCounter: TypedContractMethod<[], [bigint], "view">;

  projectNFT: TypedContractMethod<[], [string], "view">;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  requireApproval: TypedContractMethod<[], [boolean], "view">;

  setComplianceImplementation: TypedContractMethod<
    [_impl: AddressLike],
    [void],
    "nonpayable"
  >;

  setCreationFee: TypedContractMethod<
    [_fee: BigNumberish],
    [void],
    "nonpayable"
  >;

  setDefaultPriceFeed: TypedContractMethod<
    [_priceFeed: AddressLike],
    [void],
    "nonpayable"
  >;

  setDeployerApproval: TypedContractMethod<
    [_deployer: AddressLike, _approved: boolean],
    [void],
    "nonpayable"
  >;

  setDividendDistributorImplementation: TypedContractMethod<
    [_impl: AddressLike],
    [void],
    "nonpayable"
  >;

  setEscrowVaultImplementation: TypedContractMethod<
    [_impl: AddressLike],
    [void],
    "nonpayable"
  >;

  setIdentityRegistry: TypedContractMethod<
    [_registry: AddressLike],
    [void],
    "nonpayable"
  >;

  setPlatformFeeBps: TypedContractMethod<
    [_feeBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPlatformFeeRecipient: TypedContractMethod<
    [_recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  setProjectNFT: TypedContractMethod<
    [_projectNFT: AddressLike],
    [void],
    "nonpayable"
  >;

  setRequireApproval: TypedContractMethod<
    [_require: boolean],
    [void],
    "nonpayable"
  >;

  setSecurityTokenImplementation: TypedContractMethod<
    [_impl: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  upgradeTo: TypedContractMethod<
    [newImplementation: AddressLike],
    [void],
    "nonpayable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approvedDeployers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "batchSetDeployerApproval"
  ): TypedContractMethod<
    [_deployers: AddressLike[], _approved: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "creationFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deactivateProject"
  ): TypedContractMethod<[_projectId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "defaultPriceFeed"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "deployProject"
  ): TypedContractMethod<
    [
      _name: string,
      _symbol: string,
      _category: string,
      _maxSupply: BigNumberish,
      _fundingGoal: BigNumberish,
      _deadlineDays: BigNumberish,
      _paymentToken: AddressLike,
      _metadataUri: string
    ],
    [
      [bigint, string, string, string] & {
        projectId: bigint;
        securityToken: string;
        escrowVault: string;
        compliance: string;
      }
    ],
    "payable"
  >;
  getFunction(
    nameOrSignature: "deployerProjects"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "deployments"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, string, bigint, boolean] & {
        projectId: bigint;
        securityToken: string;
        escrowVault: string;
        compliance: string;
        deployer: string;
        deployedAt: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getActiveProjects"
  ): TypedContractMethod<
    [_offset: BigNumberish, _limit: BigNumberish],
    [bigint[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDeployerProjectCount"
  ): TypedContractMethod<[_deployer: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDeployerProjects"
  ): TypedContractMethod<[_deployer: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getDeployment"
  ): TypedContractMethod<
    [_projectId: BigNumberish],
    [RWALaunchpadFactory.DeploymentRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getImplementations"
  ): TypedContractMethod<
    [],
    [RWALaunchpadFactory.ImplementationAddressesStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "implementations"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, string, string] & {
        securityToken: string;
        escrowVault: string;
        compliance: string;
        identityRegistry: string;
        dividendDistributor: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      _admin: AddressLike,
      _securityTokenImpl: AddressLike,
      _escrowVaultImpl: AddressLike,
      _complianceImpl: AddressLike,
      _identityRegistry: AddressLike,
      _projectNFT: AddressLike,
      _feeRecipient: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isDeployerApproved"
  ): TypedContractMethod<[_deployer: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "platformFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "platformFeeRecipient"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "projectCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "projectNFT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requireApproval"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "setComplianceImplementation"
  ): TypedContractMethod<[_impl: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setCreationFee"
  ): TypedContractMethod<[_fee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDefaultPriceFeed"
  ): TypedContractMethod<[_priceFeed: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDeployerApproval"
  ): TypedContractMethod<
    [_deployer: AddressLike, _approved: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setDividendDistributorImplementation"
  ): TypedContractMethod<[_impl: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setEscrowVaultImplementation"
  ): TypedContractMethod<[_impl: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setIdentityRegistry"
  ): TypedContractMethod<[_registry: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPlatformFeeBps"
  ): TypedContractMethod<[_feeBps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPlatformFeeRecipient"
  ): TypedContractMethod<[_recipient: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setProjectNFT"
  ): TypedContractMethod<[_projectNFT: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRequireApproval"
  ): TypedContractMethod<[_require: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSecurityTokenImplementation"
  ): TypedContractMethod<[_impl: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeTo"
  ): TypedContractMethod<
    [newImplementation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getEvent(
    key: "AdminChanged"
  ): TypedContractEvent<
    AdminChangedEvent.InputTuple,
    AdminChangedEvent.OutputTuple,
    AdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "BeaconUpgraded"
  ): TypedContractEvent<
    BeaconUpgradedEvent.InputTuple,
    BeaconUpgradedEvent.OutputTuple,
    BeaconUpgradedEvent.OutputObject
  >;
  getEvent(
    key: "CreationFeeUpdated"
  ): TypedContractEvent<
    CreationFeeUpdatedEvent.InputTuple,
    CreationFeeUpdatedEvent.OutputTuple,
    CreationFeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "DefaultPriceFeedUpdated"
  ): TypedContractEvent<
    DefaultPriceFeedUpdatedEvent.InputTuple,
    DefaultPriceFeedUpdatedEvent.OutputTuple,
    DefaultPriceFeedUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "DeployerApprovalUpdated"
  ): TypedContractEvent<
    DeployerApprovalUpdatedEvent.InputTuple,
    DeployerApprovalUpdatedEvent.OutputTuple,
    DeployerApprovalUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "FeeRecipientUpdated"
  ): TypedContractEvent<
    FeeRecipientUpdatedEvent.InputTuple,
    FeeRecipientUpdatedEvent.OutputTuple,
    FeeRecipientUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ImplementationUpdated"
  ): TypedContractEvent<
    ImplementationUpdatedEvent.InputTuple,
    ImplementationUpdatedEvent.OutputTuple,
    ImplementationUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PlatformFeeUpdated"
  ): TypedContractEvent<
    PlatformFeeUpdatedEvent.InputTuple,
    PlatformFeeUpdatedEvent.OutputTuple,
    PlatformFeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ProjectDeactivated"
  ): TypedContractEvent<
    ProjectDeactivatedEvent.InputTuple,
    ProjectDeactivatedEvent.OutputTuple,
    ProjectDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "ProjectDeployed"
  ): TypedContractEvent<
    ProjectDeployedEvent.InputTuple,
    ProjectDeployedEvent.OutputTuple,
    ProjectDeployedEvent.OutputObject
  >;
  getEvent(
    key: "ProjectNFTUpdated"
  ): TypedContractEvent<
    ProjectNFTUpdatedEvent.InputTuple,
    ProjectNFTUpdatedEvent.OutputTuple,
    ProjectNFTUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "AdminChanged(address,address)": TypedContractEvent<
      AdminChangedEvent.InputTuple,
      AdminChangedEvent.OutputTuple,
      AdminChangedEvent.OutputObject
    >;
    AdminChanged: TypedContractEvent<
      AdminChangedEvent.InputTuple,
      AdminChangedEvent.OutputTuple,
      AdminChangedEvent.OutputObject
    >;

    "BeaconUpgraded(address)": TypedContractEvent<
      BeaconUpgradedEvent.InputTuple,
      BeaconUpgradedEvent.OutputTuple,
      BeaconUpgradedEvent.OutputObject
    >;
    BeaconUpgraded: TypedContractEvent<
      BeaconUpgradedEvent.InputTuple,
      BeaconUpgradedEvent.OutputTuple,
      BeaconUpgradedEvent.OutputObject
    >;

    "CreationFeeUpdated(uint256,uint256)": TypedContractEvent<
      CreationFeeUpdatedEvent.InputTuple,
      CreationFeeUpdatedEvent.OutputTuple,
      CreationFeeUpdatedEvent.OutputObject
    >;
    CreationFeeUpdated: TypedContractEvent<
      CreationFeeUpdatedEvent.InputTuple,
      CreationFeeUpdatedEvent.OutputTuple,
      CreationFeeUpdatedEvent.OutputObject
    >;

    "DefaultPriceFeedUpdated(address,address)": TypedContractEvent<
      DefaultPriceFeedUpdatedEvent.InputTuple,
      DefaultPriceFeedUpdatedEvent.OutputTuple,
      DefaultPriceFeedUpdatedEvent.OutputObject
    >;
    DefaultPriceFeedUpdated: TypedContractEvent<
      DefaultPriceFeedUpdatedEvent.InputTuple,
      DefaultPriceFeedUpdatedEvent.OutputTuple,
      DefaultPriceFeedUpdatedEvent.OutputObject
    >;

    "DeployerApprovalUpdated(address,bool)": TypedContractEvent<
      DeployerApprovalUpdatedEvent.InputTuple,
      DeployerApprovalUpdatedEvent.OutputTuple,
      DeployerApprovalUpdatedEvent.OutputObject
    >;
    DeployerApprovalUpdated: TypedContractEvent<
      DeployerApprovalUpdatedEvent.InputTuple,
      DeployerApprovalUpdatedEvent.OutputTuple,
      DeployerApprovalUpdatedEvent.OutputObject
    >;

    "FeeRecipientUpdated(address,address)": TypedContractEvent<
      FeeRecipientUpdatedEvent.InputTuple,
      FeeRecipientUpdatedEvent.OutputTuple,
      FeeRecipientUpdatedEvent.OutputObject
    >;
    FeeRecipientUpdated: TypedContractEvent<
      FeeRecipientUpdatedEvent.InputTuple,
      FeeRecipientUpdatedEvent.OutputTuple,
      FeeRecipientUpdatedEvent.OutputObject
    >;

    "ImplementationUpdated(string,address,address)": TypedContractEvent<
      ImplementationUpdatedEvent.InputTuple,
      ImplementationUpdatedEvent.OutputTuple,
      ImplementationUpdatedEvent.OutputObject
    >;
    ImplementationUpdated: TypedContractEvent<
      ImplementationUpdatedEvent.InputTuple,
      ImplementationUpdatedEvent.OutputTuple,
      ImplementationUpdatedEvent.OutputObject
    >;

    "Initialized(uint8)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PlatformFeeUpdated(uint256,uint256)": TypedContractEvent<
      PlatformFeeUpdatedEvent.InputTuple,
      PlatformFeeUpdatedEvent.OutputTuple,
      PlatformFeeUpdatedEvent.OutputObject
    >;
    PlatformFeeUpdated: TypedContractEvent<
      PlatformFeeUpdatedEvent.InputTuple,
      PlatformFeeUpdatedEvent.OutputTuple,
      PlatformFeeUpdatedEvent.OutputObject
    >;

    "ProjectDeactivated(uint256)": TypedContractEvent<
      ProjectDeactivatedEvent.InputTuple,
      ProjectDeactivatedEvent.OutputTuple,
      ProjectDeactivatedEvent.OutputObject
    >;
    ProjectDeactivated: TypedContractEvent<
      ProjectDeactivatedEvent.InputTuple,
      ProjectDeactivatedEvent.OutputTuple,
      ProjectDeactivatedEvent.OutputObject
    >;

    "ProjectDeployed(uint256,address,address,address,address)": TypedContractEvent<
      ProjectDeployedEvent.InputTuple,
      ProjectDeployedEvent.OutputTuple,
      ProjectDeployedEvent.OutputObject
    >;
    ProjectDeployed: TypedContractEvent<
      ProjectDeployedEvent.InputTuple,
      ProjectDeployedEvent.OutputTuple,
      ProjectDeployedEvent.OutputObject
    >;

    "ProjectNFTUpdated(address,address)": TypedContractEvent<
      ProjectNFTUpdatedEvent.InputTuple,
      ProjectNFTUpdatedEvent.OutputTuple,
      ProjectNFTUpdatedEvent.OutputObject
    >;
    ProjectNFTUpdated: TypedContractEvent<
      ProjectNFTUpdatedEvent.InputTuple,
      ProjectNFTUpdatedEvent.OutputTuple,
      ProjectNFTUpdatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
